DROP TABLE FGS.WIP_MASTER_MV CASCADE CONSTRAINTS;

CREATE TABLE FGS.WIP_MASTER_MV
(
  SLNO          VARCHAR2(30 BYTE)               NOT NULL,
  WIP_DATE      DATE                            NOT NULL,
  P_CODE        VARCHAR2(15 BYTE),
  BATCH_NO      VARCHAR2(18 BYTE),
  MNL_BATCH_NO  VARCHAR2(45 BYTE),
  BATCH_SIZE    VARCHAR2(30 BYTE),
  ISSU_DATE     DATE,
  MFG_STEPS     VARCHAR2(600 BYTE),
  REMARKS       VARCHAR2(600 BYTE),
  USER_ID       VARCHAR2(30 BYTE),
  ENTER_DT      DATE,
  PROD_TYPE     VARCHAR2(6 BYTE),
  PCAT_CODE     VARCHAR2(15 BYTE),
  COM_CODE      VARCHAR2(9 BYTE),
  PRS_CODE      VARCHAR2(12 BYTE)
)
TABLESPACE FGS_DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


DROP TABLE FGS.YM_PRODUCTION CASCADE CONSTRAINTS;

CREATE TABLE FGS.YM_PRODUCTION
(
  MNYR            VARCHAR2(6 BYTE),
  P_CODE          VARCHAR2(4 BYTE),
  BATCH_QNTY      NUMBER,
  BATCH_SIZE      NUMBER,
  BATCH_SIZE_UOM  VARCHAR2(5 BYTE),
  NOB             NUMBER,
  ACT_YIELD       NUMBER,
  BATCH_QNTY_UOM  VARCHAR2(5 BYTE)
)
TABLESPACE FGS_DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          512K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


DROP TABLE FGS.TEMPP_QA_RELS_ITEM CASCADE CONSTRAINTS;

CREATE TABLE FGS.TEMPP_QA_RELS_ITEM
(
  RELS_NO     VARCHAR2(10 BYTE),
  PROD_TYPE   VARCHAR2(12 BYTE),
  P_CODE      VARCHAR2(5 BYTE),
  PROD_BATCH  VARCHAR2(6 BYTE),
  MFG_DATE    DATE,
  EXP_DATE    DATE,
  PROD_QNTY   NUMBER(10),
  PROD_RATE   NUMBER(8,2),
  PROD_VAT    NUMBER(8,2),
  ACT_VALUE   NUMBER(15,2),
  VAT_VALUE   NUMBER(15,2),
  NET_VALUE   NUMBER(15,2),
  QA_RESULT   VARCHAR2(2 BYTE),
  RETEN_QNTY  NUMBER(12),
  VALID_QNTY  NUMBER(12),
  OTHER_QNTY  NUMBER(12),
  QC_REF_NO   VARCHAR2(15 BYTE),
  QA_APRV_BY  VARCHAR2(10 BYTE),
  QA_APRV_DT  DATE,
  BRK_QNTY    NUMBER(10),
  DMG_QNTY    NUMBER(10),
  APRV_BY_GM  VARCHAR2(10 BYTE),
  APRV_DT_GM  DATE,
  P_N_CODE    VARCHAR2(5 BYTE),
  PACK_SIZE   VARCHAR2(10 BYTE),
  PACK_SIZE1  NUMBER(2),
  PACK_SIZE2  NUMBER(3)
)
TABLESPACE FGS_DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


ALTER TABLE FGS.REC_MAIN
 DROP PRIMARY KEY CASCADE;

DROP TABLE FGS.REC_MAIN CASCADE CONSTRAINTS;

CREATE TABLE FGS.REC_MAIN
(
  RECNO             VARCHAR2(10 BYTE),
  REC_DATE          DATE,
  REC_FROM          VARCHAR2(5 BYTE),
  REC_TO            VARCHAR2(5 BYTE),
  CHALNO            VARCHAR2(10 BYTE),
  CHALDATE          DATE,
  TRNSTAT           VARCHAR2(1 BYTE),
  USER_ID           VARCHAR2(10 BYTE),
  ENTER_DT          DATE,
  REC_TYPE          VARCHAR2(1 BYTE),
  IS_APP_UNIT_HEAD  VARCHAR2(1 BYTE),
  UNIT_HEAD_CODE    VARCHAR2(10 BYTE),
  IS_FGS_REC        VARCHAR2(1 BYTE),
  REC_BY            VARCHAR2(10 BYTE)
)
TABLESPACE FGS_DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


DROP TABLE FGS.REC_ITEM_GTEMP01 CASCADE CONSTRAINTS;

CREATE TABLE FGS.REC_ITEM_GTEMP01
(
  RECNO         VARCHAR2(10 BYTE),
  P_CODE        VARCHAR2(4 BYTE),
  PROD_BATCH    VARCHAR2(6 BYTE),
  PRODQNTY      NUMBER(12),
  PRODRATE      NUMBER(8,2),
  VAT_RATE      NUMBER(8,2),
  ACTVALUE      NUMBER(15,2),
  VATVALUE      NUMBER(15,2),
  NETVALUE      NUMBER(15,2),
  TRNSTAT       VARCHAR2(1 BYTE),
  USER_ID       VARCHAR2(10 BYTE),
  ENTER_DT      DATE,
  MFG_DATE      DATE,
  EXP_DATE      DATE,
  REMARKS       VARCHAR2(100 BYTE),
  BATCH_MANUAL  VARCHAR2(6 BYTE)
)
TABLESPACE FGS_DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


ALTER TABLE FGS.REC_ITEM
 DROP PRIMARY KEY CASCADE;

DROP TABLE FGS.REC_ITEM CASCADE CONSTRAINTS;

CREATE TABLE FGS.REC_ITEM
(
  RECNO         VARCHAR2(10 BYTE),
  P_CODE        VARCHAR2(4 BYTE),
  PROD_BATCH    VARCHAR2(6 BYTE),
  PRODQNTY      NUMBER(12),
  PRODRATE      NUMBER(8,2),
  VAT_RATE      NUMBER(8,2),
  ACTVALUE      NUMBER(15,2),
  VATVALUE      NUMBER(15,2),
  NETVALUE      NUMBER(15,2),
  TRNSTAT       VARCHAR2(1 BYTE),
  USER_ID       VARCHAR2(10 BYTE),
  ENTER_DT      DATE,
  MFG_DATE      DATE,
  EXP_DATE      DATE,
  REMARKS       VARCHAR2(100 BYTE),
  BATCH_MANUAL  VARCHAR2(6 BYTE)
)
TABLESPACE FGS_DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


ALTER TABLE FGS.QA_SAMP_MAIN
 DROP PRIMARY KEY CASCADE;

DROP TABLE FGS.QA_SAMP_MAIN CASCADE CONSTRAINTS;

CREATE TABLE FGS.QA_SAMP_MAIN
(
  DISP_SLNO         VARCHAR2(10 BYTE),
  DISP_DATE         DATE,
  DISP_FROM         VARCHAR2(5 BYTE),
  DISP_TO           VARCHAR2(5 BYTE),
  DISP_CHALNO       VARCHAR2(10 BYTE),
  DISP_TYPE         VARCHAR2(1 BYTE),
  DISP_STAT         VARCHAR2(1 BYTE),
  USER_ID           VARCHAR2(10 BYTE),
  ENTER_DT          DATE,
  IS_TEST_COMPLETE  VARCHAR2(1 BYTE),
  IS_TRANSFER       VARCHAR2(1 BYTE)
)
TABLESPACE FGS_DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


DROP TABLE FGS.QA_SAMP_ITEM_TEMP CASCADE CONSTRAINTS;

CREATE TABLE FGS.QA_SAMP_ITEM_TEMP
(
  DISP_SLNO   VARCHAR2(10 BYTE),
  P_CODE      VARCHAR2(5 BYTE),
  PROD_BATCH  VARCHAR2(6 BYTE),
  DISP_QNTY   NUMBER(10),
  PROD_RATE   NUMBER(8,2),
  PROD_VAT    NUMBER(8,2),
  ACT_VALUE   NUMBER(15,2),
  VAT_VALUE   NUMBER(15,2),
  NET_VALUE   NUMBER(15,2),
  TRNS_STAT   VARCHAR2(1 BYTE),
  USER_ID     VARCHAR2(10 BYTE),
  ENTER_DT    DATE,
  MANUF_DT    DATE,
  EXP_DT      DATE
)
TABLESPACE FGS_DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


ALTER TABLE FGS.QA_SAMP_ITEM
 DROP PRIMARY KEY CASCADE;

DROP TABLE FGS.QA_SAMP_ITEM CASCADE CONSTRAINTS;

CREATE TABLE FGS.QA_SAMP_ITEM
(
  DISP_SLNO       VARCHAR2(10 BYTE),
  P_CODE          VARCHAR2(5 BYTE),
  PROD_BATCH      VARCHAR2(6 BYTE),
  DISP_QNTY       NUMBER(10),
  PROD_RATE       NUMBER(8,2),
  PROD_VAT        NUMBER(8,2),
  ACT_VALUE       NUMBER(15,2),
  VAT_VALUE       NUMBER(15,2),
  NET_VALUE       NUMBER(15,2),
  TRNS_STAT       VARCHAR2(1 BYTE),
  USER_ID         VARCHAR2(10 BYTE),
  ENTER_DT        DATE,
  MFG_DT          DATE,
  EXP_DT          DATE,
  MNL_PROD_BATCH  VARCHAR2(15 BYTE),
  DISP_TO         VARCHAR2(5 BYTE),
  REC_BY          VARCHAR2(5 BYTE)
)
TABLESPACE FGS_DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


ALTER TABLE FGS.QA_SAMP_INFO
 DROP PRIMARY KEY CASCADE;

DROP TABLE FGS.QA_SAMP_INFO CASCADE CONSTRAINTS;

CREATE TABLE FGS.QA_SAMP_INFO
(
  SAMP_SLNO            VARCHAR2(10 BYTE),
  SAMP_DT              DATE,
  DISP_SLNO            VARCHAR2(10 BYTE),
  SAMP_TAKEN_CODE      VARCHAR2(5 BYTE),
  SAMP_QNTY            NUMBER(8),
  SAMP_ANAL            NUMBER(8),
  SAMP_RETEN           NUMBER(8),
  SAMP_TYPE            VARCHAR2(1 BYTE),
  RETEN_SAMP_REC_CODE  VARCHAR2(5 BYTE),
  USER_ID              VARCHAR2(5 BYTE),
  ENTER_DT             DATE,
  TOT_QNTY             NUMBER(8),
  PD_QNTY              NUMBER(8),
  PD_REC_CODE          VARCHAR2(5 BYTE),
  QA_RESULT            VARCHAR2(1 BYTE),
  QA_REF_NO            VARCHAR2(15 BYTE),
  CHECK_BY             VARCHAR2(5 BYTE),
  APPROV_BY            VARCHAR2(5 BYTE),
  QA_MNL_REF_NO        VARCHAR2(20 BYTE)
)
TABLESPACE FGS_DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


ALTER TABLE FGS.QA_RELS_MAIN_MV
 DROP PRIMARY KEY CASCADE;

DROP TABLE FGS.QA_RELS_MAIN_MV CASCADE CONSTRAINTS;

CREATE TABLE FGS.QA_RELS_MAIN_MV
(
  RELS_NO      VARCHAR2(30 BYTE)                NOT NULL,
  RELS_DT      DATE,
  PF_RELS_NO   VARCHAR2(30 BYTE),
  USER_ID      VARCHAR2(30 BYTE),
  ENTER_DT     DATE,
  COM_CODE     VARCHAR2(9 BYTE),
  RELS_NO_MNL  VARCHAR2(45 BYTE),
  REMARKS      VARCHAR2(300 BYTE),
  DISP_NO_MNL  VARCHAR2(45 BYTE)
)
TABLESPACE FGS_DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          4M
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


DROP TABLE FGS.QA_RELS_ITEM_TEMP CASCADE CONSTRAINTS;

CREATE TABLE FGS.QA_RELS_ITEM_TEMP
(
  RELS_NO      VARCHAR2(10 BYTE),
  PROD_TYPE    VARCHAR2(12 BYTE),
  P_CODE       VARCHAR2(5 BYTE),
  PROD_BATCH   VARCHAR2(6 BYTE),
  MFG_DATE     DATE,
  EXP_DATE     DATE,
  PROD_QNTY    NUMBER(10),
  PROD_RATE    NUMBER(8,2),
  PROD_VAT     NUMBER(8,2),
  ACT_VALUE    NUMBER(15,2),
  VAT_VALUE    NUMBER(15,2),
  NET_VALUE    NUMBER(15,2),
  QA_RESULT    VARCHAR2(2 BYTE),
  RETEN_QNTY   NUMBER(12),
  VALID_QNTY   NUMBER(12),
  OTHER_QNTY   NUMBER(12),
  QC_REF_NO    VARCHAR2(15 BYTE),
  QA_APRV_BY   VARCHAR2(10 BYTE),
  QA_APRV_DT   DATE,
  BRK_QNTY     NUMBER(10),
  DMG_QNTY     NUMBER(10),
  APRV_BY_GM   VARCHAR2(10 BYTE),
  APRV_DT_GM   DATE,
  P_N_CODE     VARCHAR2(5 BYTE),
  PACK_SIZE    VARCHAR2(10 BYTE),
  PACK_SIZE1   NUMBER(2),
  PACK_SIZE2   NUMBER(3),
  APRV_QNTY    NUMBER(10),
  DISP_BY      VARCHAR2(10 BYTE),
  DISP_DT      DATE,
  DISP_NO_MNL  VARCHAR2(15 BYTE),
  MAN_HRS      VARCHAR2(10 BYTE),
  MC_HRS       VARCHAR2(10 BYTE),
  MAN_MI       VARCHAR2(2 BYTE),
  MC_MI        VARCHAR2(2 BYTE),
  CS_RCV       VARCHAR2(1 BYTE),
  CS_RCV_BY    VARCHAR2(10 BYTE),
  CS_RCV_DT    DATE
)
TABLESPACE FGS_DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          320K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


ALTER TABLE FGS.QA_RELS_ITEM_MV
 DROP PRIMARY KEY CASCADE;

DROP TABLE FGS.QA_RELS_ITEM_MV CASCADE CONSTRAINTS;

CREATE TABLE FGS.QA_RELS_ITEM_MV
(
  RELS_NO      VARCHAR2(30 BYTE)                NOT NULL,
  PROD_TYPE    VARCHAR2(36 BYTE)                NOT NULL,
  P_CODE       VARCHAR2(15 BYTE)                NOT NULL,
  PROD_BATCH   VARCHAR2(18 BYTE)                NOT NULL,
  MFG_DATE     DATE,
  EXP_DATE     DATE,
  PROD_QNTY    NUMBER(10),
  PROD_RATE    NUMBER(8,2),
  PROD_VAT     NUMBER(8,2),
  ACT_VALUE    NUMBER(15,2),
  VAT_VALUE    NUMBER(15,2),
  NET_VALUE    NUMBER(15,2),
  QA_RESULT    VARCHAR2(6 BYTE),
  RETEN_QNTY   NUMBER(12),
  VALID_QNTY   NUMBER(12),
  OTHER_QNTY   NUMBER(12),
  QC_REF_NO    VARCHAR2(45 BYTE),
  QA_APRV_BY   VARCHAR2(30 BYTE),
  QA_APRV_DT   DATE,
  BRK_QNTY     NUMBER(10),
  DMG_QNTY     NUMBER(10),
  APRV_BY_GM   VARCHAR2(30 BYTE),
  APRV_DT_GM   DATE,
  P_N_CODE     VARCHAR2(15 BYTE)                NOT NULL,
  PACK_SIZE    VARCHAR2(30 BYTE),
  PACK_SIZE1   NUMBER(2),
  PACK_SIZE2   NUMBER(3),
  APRV_QNTY    NUMBER(10),
  DISP_BY      VARCHAR2(30 BYTE),
  DISP_DT      DATE,
  DISP_NO_MNL  VARCHAR2(45 BYTE),
  MAN_HRS      VARCHAR2(30 BYTE),
  MC_HRS       VARCHAR2(30 BYTE),
  MAN_MI       VARCHAR2(6 BYTE),
  MC_MI        VARCHAR2(6 BYTE),
  CS_RCV       VARCHAR2(3 BYTE),
  CS_RCV_BY    VARCHAR2(30 BYTE),
  CS_RCV_DT    DATE
)
TABLESPACE FGS_DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          9M
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


ALTER TABLE FGS.PROD_STOK
 DROP PRIMARY KEY CASCADE;

DROP TABLE FGS.PROD_STOK CASCADE CONSTRAINTS;

CREATE TABLE FGS.PROD_STOK
(
  P_CODE      VARCHAR2(4 BYTE),
  PROD_BATCH  VARCHAR2(6 BYTE),
  IN_QNTY     NUMBER(8),
  OUT_QNTY    NUMBER(8),
  STK_QNTY    NUMBER(8),
  BRK_QNTY    NUMBER(8),
  DMG_QNTY    NUMBER(8),
  CDMG_QNTY   NUMBER(8),
  DEXP_QNTY   NUMBER(8),
  MFG_DATE    DATE,
  EXP_DATE    DATE
)
TABLESPACE FGS_DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


DROP TABLE FGS.PROD_BATCH_COST CASCADE CONSTRAINTS;

CREATE TABLE FGS.PROD_BATCH_COST
(
  PBC_SLNO        VARCHAR2(10 BYTE),
  P_CODE          VARCHAR2(5 BYTE),
  PROD_BATCH      VARCHAR2(6 BYTE),
  PROD_BATCH_MNL  VARCHAR2(10 BYTE),
  COST_PER_BOX    NUMBER,
  RM_COST         NUMBER,
  PM_COST         NUMBER,
  VC_COST         NUMBER,
  FC_COST         NUMBER,
  USER_ID         VARCHAR2(10 BYTE),
  ENTER_DT        DATE
)
TABLESPACE FGS_DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


DROP TABLE FGS.PRODUCT_VET_TO_HHD CASCADE CONSTRAINTS;

CREATE TABLE FGS.PRODUCT_VET_TO_HHD
(
  P_CODE  VARCHAR2(15 BYTE)                     NOT NULL,
  P_DESC  VARCHAR2(300 BYTE)
)
TABLESPACE FGS_DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


DROP TABLE FGS.PF_RELS_TEMP CASCADE CONSTRAINTS;

CREATE TABLE FGS.PF_RELS_TEMP
(
  PF_RELS_NO      VARCHAR2(10 BYTE),
  PROD_TYPE       VARCHAR2(12 BYTE),
  P_CODE          VARCHAR2(4 BYTE),
  PROD_BATCH      VARCHAR2(6 BYTE),
  PROD_BATCH_MNL  VARCHAR2(15 BYTE),
  MFG_DATE        DATE,
  EXP_DATE        DATE,
  PROD_QNTY       NUMBER(12),
  PROD_RATE       NUMBER(8,2),
  VAT_RATE        NUMBER(8,2),
  ACT_VALUE       NUMBER(15,2),
  VAT_VALUE       NUMBER(15,2),
  NET_VALUE       NUMBER(15,2),
  PF_APRV_BY      VARCHAR2(10 BYTE),
  PF_APRV_DT      DATE,
  P_N_CODE        VARCHAR2(5 BYTE),
  PACK_SIZE       VARCHAR2(10 BYTE),
  PACK_SIZE1      NUMBER(2),
  PACK_SIZE2      NUMBER(3)
)
TABLESPACE FGS_DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


ALTER TABLE FGS.PF_RELS_MAIN_TEST
 DROP PRIMARY KEY CASCADE;

DROP TABLE FGS.PF_RELS_MAIN_TEST CASCADE CONSTRAINTS;

CREATE TABLE FGS.PF_RELS_MAIN_TEST
(
  PF_RELS_NO    VARCHAR2(10 BYTE)               NOT NULL,
  PF_RELS_DT    DATE,
  ACT_VALUE     NUMBER(15,2),
  VAT_VALUE     NUMBER(15,2),
  NET_VALUE     NUMBER(15,2),
  USER_ID       VARCHAR2(10 BYTE),
  ENTER_DT      DATE,
  COM_CODE      VARCHAR2(3 BYTE),
  TRANS_NO_MNL  VARCHAR2(15 BYTE),
  REMARKS       VARCHAR2(100 BYTE)
)
TABLESPACE FGS_DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          3M
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


ALTER TABLE FGS.PF_RELS_MAIN_MV
 DROP PRIMARY KEY CASCADE;

DROP TABLE FGS.PF_RELS_MAIN_MV CASCADE CONSTRAINTS;

CREATE TABLE FGS.PF_RELS_MAIN_MV
(
  PF_RELS_NO    VARCHAR2(30 BYTE)               NOT NULL,
  PF_RELS_DT    DATE,
  ACT_VALUE     NUMBER(15,2),
  VAT_VALUE     NUMBER(15,2),
  NET_VALUE     NUMBER(15,2),
  USER_ID       VARCHAR2(30 BYTE),
  ENTER_DT      DATE,
  COM_CODE      VARCHAR2(9 BYTE),
  TRANS_NO_MNL  VARCHAR2(45 BYTE),
  REMARKS       VARCHAR2(300 BYTE)
)
TABLESPACE FGS_DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          4M
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


ALTER TABLE FGS.PF_RELS_ITEM_MV
 DROP PRIMARY KEY CASCADE;

DROP TABLE FGS.PF_RELS_ITEM_MV CASCADE CONSTRAINTS;

CREATE TABLE FGS.PF_RELS_ITEM_MV
(
  PF_RELS_NO      VARCHAR2(30 BYTE)             NOT NULL,
  PROD_TYPE       VARCHAR2(36 BYTE)             NOT NULL,
  P_CODE          VARCHAR2(12 BYTE)             NOT NULL,
  PROD_BATCH      VARCHAR2(18 BYTE)             NOT NULL,
  PROD_BATCH_MNL  VARCHAR2(45 BYTE),
  MFG_DATE        DATE,
  EXP_DATE        DATE,
  PROD_QNTY       NUMBER(12),
  PROD_RATE       NUMBER(8,2),
  VAT_RATE        NUMBER(8,2),
  ACT_VALUE       NUMBER(15,2),
  VAT_VALUE       NUMBER(15,2),
  NET_VALUE       NUMBER(15,2),
  PF_APRV_BY      VARCHAR2(30 BYTE),
  PF_APRV_DT      DATE,
  P_N_CODE        VARCHAR2(15 BYTE)             NOT NULL,
  PACK_SIZE       VARCHAR2(30 BYTE),
  PACK_SIZE1      NUMBER(2),
  PACK_SIZE2      NUMBER(3),
  APRV_QNTY       NUMBER(10),
  MAN_HRS         VARCHAR2(30 BYTE),
  MC_HRS          VARCHAR2(30 BYTE),
  MAN_MI          VARCHAR2(6 BYTE),
  MC_MI           VARCHAR2(6 BYTE),
  ORD_NO          VARCHAR2(60 BYTE),
  ORD_DT          DATE,
  LC_NO           VARCHAR2(300 BYTE),
  LC_DT           DATE,
  RELS_STATUS     VARCHAR2(3 BYTE)
)
TABLESPACE FGS_DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          7M
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


DROP TABLE FGS.MON_CLS_STK CASCADE CONSTRAINTS;

CREATE TABLE FGS.MON_CLS_STK
(
  CALCODE        VARCHAR2(6 BYTE)               NOT NULL,
  P_CODE         VARCHAR2(5 BYTE)               NOT NULL,
  PROD_BATCH     VARCHAR2(6 BYTE)               NOT NULL,
  PROD_TYPE      VARCHAR2(1 BYTE)               NOT NULL,
  OPEN_STK       NUMBER(10),
  CLS_STK        NUMBER(10),
  OPEN_STK_UNIT  NUMBER(10),
  USER_ID        VARCHAR2(10 BYTE),
  ENTER_DT       VARCHAR2(30 BYTE),
  STR_FLAG       VARCHAR2(1 BYTE)               NOT NULL,
  PROD_RATE      NUMBER(7,2),
  PROD_VAT       NUMBER(7,2),
  PROD_VALUE     NUMBER,
  FDATE          DATE,
  TDATE          DATE,
  P_N_CODE       VARCHAR2(5 BYTE)
)
TABLESPACE FGS_DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          128K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


DROP TABLE FGS.MI_REMOVE_P_LIST CASCADE CONSTRAINTS;

CREATE TABLE FGS.MI_REMOVE_P_LIST
(
  P_CODE      VARCHAR2(10 BYTE),
  PROD_BATCH  VARCHAR2(10 BYTE)
)
TABLESPACE FGS_DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


ALTER TABLE FGS.MAT_COMMENTS
 DROP PRIMARY KEY CASCADE;

DROP TABLE FGS.MAT_COMMENTS CASCADE CONSTRAINTS;

CREATE TABLE FGS.MAT_COMMENTS
(
  OBJECT_NAME  VARCHAR2(50 BYTE),
  OBJECT_COM   VARCHAR2(200 BYTE)
)
TABLESPACE FGS_DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


DROP TABLE FGS.FGS_WIP_MVW CASCADE CONSTRAINTS;

CREATE TABLE FGS.FGS_WIP_MVW
(
  P_CODE      VARCHAR2(15 BYTE),
  MBATCH_NO   VARCHAR2(45 BYTE),
  PROD_BATCH  VARCHAR2(18 BYTE),
  BATCH_SIZE  NUMBER(16,6),
  ISSU_DATE   DATE,
  NOD         NUMBER,
  PCAT_CODE   VARCHAR2(15 BYTE)
)
TABLESPACE FGS_DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


DROP TABLE FGS.FGS_WIP_AHD_MVW CASCADE CONSTRAINTS;

CREATE TABLE FGS.FGS_WIP_AHD_MVW
(
  P_CODE      VARCHAR2(15 BYTE),
  MBATCH_NO   VARCHAR2(45 BYTE),
  PROD_BATCH  VARCHAR2(18 BYTE),
  BATCH_SIZE  NUMBER(16,6),
  ISSU_DATE   DATE,
  NOD         NUMBER,
  PCAT_CODE   VARCHAR2(15 BYTE)
)
TABLESPACE FGS_DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


DROP TABLE FGS.FGS_TYPE CASCADE CONSTRAINTS;

CREATE TABLE FGS.FGS_TYPE
(
  TTYPE        VARCHAR2(1 BYTE),
  F_TYPE       VARCHAR2(1 BYTE),
  F_TYPE_DESC  VARCHAR2(50 BYTE)
)
TABLESPACE FGS_DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


ALTER TABLE FGS.FGS_TRNS_PRDN
 DROP PRIMARY KEY CASCADE;

DROP TABLE FGS.FGS_TRNS_PRDN CASCADE CONSTRAINTS;

CREATE TABLE FGS.FGS_TRNS_PRDN
(
  SL_NO       VARCHAR2(9 BYTE)                  NOT NULL,
  PCAT_CODE   VARCHAR2(3 BYTE),
  P_CODE      VARCHAR2(4 BYTE)                  NOT NULL,
  BATCH_NO    VARCHAR2(6 BYTE)                  NOT NULL,
  MFG_DATE    DATE,
  EXP_DATE    DATE,
  S_FULL      NUMBER(6),
  S_LOOSE     NUMBER(6),
  I_FULL      NUMBER(6),
  I_LOOSE     NUMBER(6),
  G_TOTAL     NUMBER(10),
  UNIT        NUMBER(10),
  TYPE        VARCHAR2(1 BYTE),
  REMARKS     VARCHAR2(50 BYTE),
  TRNS_BY     VARCHAR2(6 BYTE),
  TRNS_DATE   VARCHAR2(30 BYTE),
  TTYPE       VARCHAR2(1 BYTE),
  MON_CODE    VARCHAR2(2 BYTE),
  YEAR_CODE   VARCHAR2(4 BYTE),
  G_TOT_RECV  NUMBER(10),
  PROD_USE    VARCHAR2(1 BYTE)                  NOT NULL,
  ENTER_DT    VARCHAR2(30 BYTE),
  RECV_FROM   VARCHAR2(1 BYTE),
  P_N_CODE    VARCHAR2(5 BYTE),
  RECON_STAT  VARCHAR2(1 BYTE),
  PRV_P_CODE  VARCHAR2(4 BYTE)
)
TABLESPACE FGS_DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          8M
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON TABLE FGS.FGS_TRNS_PRDN IS 'snapshot table for snapshot FGS.FGS_TRNS_PRDN';


DROP TABLE FGS.FGS_PROD_BATCH1 CASCADE CONSTRAINTS;

CREATE TABLE FGS.FGS_PROD_BATCH1
(
  P_CODE         VARCHAR2(4 BYTE)               NOT NULL,
  BATCH_NO       VARCHAR2(6 BYTE)               NOT NULL,
  COMM_QNTY      NUMBER,
  SAMP_QNTY      NUMBER,
  PSAMP_QNTY     NUMBER,
  SACMO_QNTY     NUMBER,
  INTERNEE_QNTY  NUMBER,
  INST_QNTY      NUMBER,
  EXP_QNTY       NUMBER,
  QA_QNTY        NUMBER,
  PD_QNTY        NUMBER,
  LK_QNTY        NUMBER,
  WF_QNTY        NUMBER,
  ENTER_DT       VARCHAR2(30 BYTE),
  T_DATE         VARCHAR2(30 BYTE),
  TOTAL_YIELD    NUMBER,
  REWORK_QNTY    NUMBER,
  PROD_USE       VARCHAR2(1 BYTE),
  QA_RECV        VARCHAR2(1 BYTE)
)
TABLESPACE FGS_DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          2M
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


ALTER TABLE FGS.FGS_MON_OPN_STK
 DROP PRIMARY KEY CASCADE;

DROP TABLE FGS.FGS_MON_OPN_STK CASCADE CONSTRAINTS;

CREATE TABLE FGS.FGS_MON_OPN_STK
(
  CALCODE       DATE                            NOT NULL,
  P_CODE        VARCHAR2(4 BYTE)                NOT NULL,
  OPN_STK_QNTY  NUMBER
)
TABLESPACE FGS_DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON TABLE FGS.FGS_MON_OPN_STK IS 'snapshot table for snapshot FGS.FGS_MON_OPN_STK';


DROP TABLE FGS.FGS_CS_RECV_TEMP CASCADE CONSTRAINTS;

CREATE TABLE FGS.FGS_CS_RECV_TEMP
(
  REC_SLNO    VARCHAR2(8 BYTE),
  REC_CHLNO   VARCHAR2(10 BYTE),
  P_CODE      VARCHAR2(5 BYTE)                  NOT NULL,
  PROD_BATCH  VARCHAR2(7 BYTE)                  NOT NULL,
  REC_QNTY    NUMBER(8),
  PROD_TYPE   VARCHAR2(1 BYTE),
  BRK_QNTY    NUMBER(6),
  DMG_QNTY    NUMBER(6),
  CDMG_QNTY   NUMBER(6),
  SHRT_QNTY   NUMBER(6),
  EXCE_QNTY   NUMBER(6)
)
TABLESPACE FGS_DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


ALTER TABLE FGS.FGS_CS_RECV1
 DROP PRIMARY KEY CASCADE;

DROP TABLE FGS.FGS_CS_RECV1 CASCADE CONSTRAINTS;

CREATE TABLE FGS.FGS_CS_RECV1
(
  INVNO         VARCHAR2(8 BYTE)                NOT NULL,
  P_CODE        VARCHAR2(4 BYTE)                NOT NULL,
  PROD_BATCH    VARCHAR2(6 BYTE)                NOT NULL,
  PROD_TYPE     VARCHAR2(1 BYTE)                NOT NULL,
  TRANSIT_QNTY  NUMBER(6),
  BRK_QNTY      NUMBER(6),
  DMG_QNTY      NUMBER(6),
  CDMG_QNTY     NUMBER(6),
  SHRT_QNTY     NUMBER(6),
  EXCE_QNTY     NUMBER(6),
  REC_QNTY      NUMBER(8),
  ENTER_DT      VARCHAR2(30 BYTE),
  P_N_CODE      VARCHAR2(5 BYTE)
)
TABLESPACE FGS_DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


DROP TABLE FGS.FGS_BRKMAIN CASCADE CONSTRAINTS;

CREATE TABLE FGS.FGS_BRKMAIN
(
  BRK_SLNO    VARCHAR2(10 BYTE)                 NOT NULL,
  BRK_DATE    DATE,
  DEPOT_CODE  VARCHAR2(2 BYTE),
  USER_ID     VARCHAR2(10 BYTE),
  ENTER_DT    VARCHAR2(30 BYTE),
  BRK_TYPE    VARCHAR2(1 BYTE),
  REC_TYPE    VARCHAR2(1 BYTE),
  CHAL_NO     VARCHAR2(10 BYTE),
  GEN_CHALNO  VARCHAR2(10 BYTE),
  GEN_CHALDT  DATE
)
TABLESPACE FGS_DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


DROP TABLE FGS.FGS_BRKITEM CASCADE CONSTRAINTS;

CREATE TABLE FGS.FGS_BRKITEM
(
  BRK_SLNO       VARCHAR2(10 BYTE)              NOT NULL,
  P_CODE         VARCHAR2(4 BYTE)               NOT NULL,
  PROD_BATCH     VARCHAR2(6 BYTE)               NOT NULL,
  RCV_QNTY       NUMBER(6),
  PROD_RATE      NUMBER(6,2),
  VAT_RATE       NUMBER(6,2),
  TP_VAL         NUMBER(12,2),
  VAT_VAL        NUMBER(12,2),
  DIS_VAL        NUMBER(12,2),
  NET_VAL        NUMBER(12,2),
  USER_ID        VARCHAR2(10 BYTE),
  ENTER_DT       VARCHAR2(30 BYTE),
  ACT_STAT       VARCHAR2(1 BYTE),
  REM_CODE       VARCHAR2(2 BYTE)               NOT NULL,
  SUB_REM_CODE   VARCHAR2(4 BYTE)               NOT NULL,
  SL_NO          VARCHAR2(9 BYTE),
  BALN_QNTY      NUMBER(10),
  COMM_BALN      NUMBER,
  INST_BALN      NUMBER,
  SAMP_BALN      NUMBER,
  PSAMP_BALN     NUMBER,
  SACMO_BALN     NUMBER,
  INTER_BALN     NUMBER,
  EXP_BALN       NUMBER,
  RCV_UNIT_QNTY  NUMBER(6),
  P_N_CODE       VARCHAR2(5 BYTE)
)
TABLESPACE FGS_DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


ALTER TABLE FGS.DISP_MAIN
 DROP PRIMARY KEY CASCADE;

DROP TABLE FGS.DISP_MAIN CASCADE CONSTRAINTS;

CREATE TABLE FGS.DISP_MAIN
(
  DISP_SLNO    VARCHAR2(10 BYTE),
  DISP_DATE    DATE,
  DISP_FROM    VARCHAR2(5 BYTE),
  DISP_TO      VARCHAR2(5 BYTE),
  DISP_CHALNO  VARCHAR2(10 BYTE),
  DISP_TYPE    VARCHAR2(1 BYTE),
  DISP_STAT    VARCHAR2(1 BYTE),
  USER_ID      VARCHAR2(10 BYTE),
  ENTER_DT     DATE
)
TABLESPACE FGS_DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


DROP TABLE FGS.DISP_ITEM_TEMP CASCADE CONSTRAINTS;

CREATE TABLE FGS.DISP_ITEM_TEMP
(
  DISP_SLNO   VARCHAR2(10 BYTE),
  P_CODE      VARCHAR2(5 BYTE),
  PROD_BATCH  VARCHAR2(6 BYTE),
  DISP_QNTY   NUMBER(10),
  PROD_RATE   NUMBER(8,2),
  PROD_VAT    NUMBER(8,2),
  ACT_VALUE   NUMBER(15,2),
  VAT_VALUE   NUMBER(15,2),
  NET_VALUE   NUMBER(15,2),
  TRNS_STAT   VARCHAR2(1 BYTE),
  USER_ID     VARCHAR2(10 BYTE),
  ENTER_DT    DATE
)
TABLESPACE FGS_DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


ALTER TABLE FGS.DISP_ITEM
 DROP PRIMARY KEY CASCADE;

DROP TABLE FGS.DISP_ITEM CASCADE CONSTRAINTS;

CREATE TABLE FGS.DISP_ITEM
(
  DISP_SLNO   VARCHAR2(10 BYTE),
  P_CODE      VARCHAR2(5 BYTE),
  PROD_BATCH  VARCHAR2(6 BYTE),
  DISP_QNTY   NUMBER(10),
  PROD_RATE   NUMBER(8,2),
  PROD_VAT    NUMBER(8,2),
  ACT_VALUE   NUMBER(15,2),
  VAT_VALUE   NUMBER(15,2),
  NET_VALUE   NUMBER(15,2),
  TRNS_STAT   VARCHAR2(1 BYTE),
  USER_ID     VARCHAR2(10 BYTE),
  ENTER_DT    DATE
)
TABLESPACE FGS_DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


ALTER TABLE FGS.CALENDER
 DROP PRIMARY KEY CASCADE;

DROP TABLE FGS.CALENDER CASCADE CONSTRAINTS;

CREATE TABLE FGS.CALENDER
(
  CALCODE      VARCHAR2(6 BYTE),
  MNAME        VARCHAR2(15 BYTE),
  FDATE        DATE,
  TDATE        DATE,
  STATUS       VARCHAR2(1 BYTE),
  STHNDVAL     NUMBER(16,2),
  CS_STKVAL    NUMBER(16,2),
  INST_STKVAL  NUMBER(16,2),
  EXP_STKVAL   NUMBER(16,2),
  SAM_STKVAL   NUMBER(16,2)
)
TABLESPACE FGS_DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


DROP TABLE FGS.REC_ITEM_GTEMP CASCADE CONSTRAINTS;

CREATE GLOBAL TEMPORARY TABLE FGS.REC_ITEM_GTEMP
(
  RECNO         VARCHAR2(10 BYTE),
  P_CODE        VARCHAR2(4 BYTE),
  PROD_BATCH    VARCHAR2(6 BYTE),
  PRODQNTY      NUMBER(12),
  PRODRATE      NUMBER(8,2),
  VAT_RATE      NUMBER(8,2),
  ACTVALUE      NUMBER(15,2),
  VATVALUE      NUMBER(15,2),
  NETVALUE      NUMBER(15,2),
  TRNSTAT       VARCHAR2(1 BYTE),
  USER_ID       VARCHAR2(10 BYTE),
  ENTER_DT      DATE,
  MFG_DATE      DATE,
  EXP_DATE      DATE,
  REMARKS       VARCHAR2(100 BYTE),
  BATCH_MANUAL  VARCHAR2(6 BYTE)
)
ON COMMIT PRESERVE ROWS
NOCACHE;


DROP TABLE FGS.PF_RELS_TMP CASCADE CONSTRAINTS;

CREATE GLOBAL TEMPORARY TABLE FGS.PF_RELS_TMP
(
  PF_RELS_NO      VARCHAR2(10 BYTE),
  PROD_TYPE       VARCHAR2(12 BYTE),
  P_CODE          VARCHAR2(4 BYTE),
  PROD_BATCH      VARCHAR2(6 BYTE),
  PROD_BATCH_MNL  VARCHAR2(15 BYTE),
  MFG_DATE        DATE,
  EXP_DATE        DATE,
  PROD_QNTY       NUMBER(12),
  PROD_RATE       NUMBER(8,2),
  VAT_RATE        NUMBER(8,2),
  ACT_VALUE       NUMBER(15,2),
  VAT_VALUE       NUMBER(15,2),
  NET_VALUE       NUMBER(15,2),
  PF_APRV_BY      VARCHAR2(10 BYTE),
  PF_APRV_DT      DATE,
  P_N_CODE        VARCHAR2(5 BYTE),
  PACK_SIZE       VARCHAR2(10 BYTE),
  PACK_SIZE1      NUMBER(2),
  PACK_SIZE2      NUMBER(3),
  MAN_HRS         VARCHAR2(10 BYTE),
  MC_HRS          VARCHAR2(10 BYTE),
  RELS_STATUS     VARCHAR2(1 BYTE),
  CHK             VARCHAR2(1 BYTE)
)
ON COMMIT PRESERVE ROWS
NOCACHE;


DROP TABLE FGS.MAT_OBJECT_GLB CASCADE CONSTRAINTS;

CREATE GLOBAL TEMPORARY TABLE FGS.MAT_OBJECT_GLB
(
  OBJECT_NAME  VARCHAR2(50 BYTE)
)
ON COMMIT PRESERVE ROWS
NOCACHE;


DROP TABLE FGS.G_QA_SAMP_ITEM CASCADE CONSTRAINTS;

CREATE GLOBAL TEMPORARY TABLE FGS.G_QA_SAMP_ITEM
(
  DISP_SLNO       VARCHAR2(10 BYTE),
  P_CODE          VARCHAR2(5 BYTE),
  PROD_BATCH      VARCHAR2(6 BYTE),
  MNL_PROD_BATCH  VARCHAR2(15 BYTE),
  DISP_QNTY       NUMBER(10),
  PROD_RATE       NUMBER(8,2),
  PROD_VAT        NUMBER(8,2),
  ACT_VALUE       NUMBER(15,2),
  VAT_VALUE       NUMBER(15,2),
  NET_VALUE       NUMBER(15,2),
  TRNS_STAT       VARCHAR2(1 BYTE),
  USER_ID         VARCHAR2(10 BYTE),
  ENTER_DT        DATE,
  MFG_DT          DATE,
  EXP_DT          DATE,
  DISP_TO         VARCHAR2(5 BYTE),
  REC_BY          VARCHAR2(5 BYTE)
)
ON COMMIT PRESERVE ROWS
NOCACHE;


DROP TABLE FGS.DISP_ITEM_GTEMP CASCADE CONSTRAINTS;

CREATE GLOBAL TEMPORARY TABLE FGS.DISP_ITEM_GTEMP
(
  DISP_SLNO   VARCHAR2(10 BYTE),
  P_CODE      VARCHAR2(5 BYTE),
  PROD_BATCH  VARCHAR2(6 BYTE),
  DISP_QNTY   NUMBER(10),
  PROD_RATE   NUMBER(8,2),
  PROD_VAT    NUMBER(8,2),
  ACT_VALUE   NUMBER(15,2),
  VAT_VALUE   NUMBER(15,2),
  NET_VALUE   NUMBER(15,2),
  TRNS_STAT   VARCHAR2(1 BYTE),
  USER_ID     VARCHAR2(10 BYTE),
  ENTER_DT    DATE
)
ON COMMIT PRESERVE ROWS
NOCACHE;


-- Note: Index I_SNAP$_FGS_WIP_AHD_MVW will be created automatically 
--       by Oracle with the associated materialized view.  The following
--       script for this index is for informational purposes only.
CREATE UNIQUE INDEX FGS.I_SNAP$_FGS_WIP_AHD_MVW ON FGS.FGS_WIP_AHD_MVW
(M_ROW$$)
LOGGING
TABLESPACE FGS_DATA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


-- Note: Index I_SNAP$_FGS_WIP_MVW will be created automatically 
--       by Oracle with the associated materialized view.  The following
--       script for this index is for informational purposes only.
CREATE UNIQUE INDEX FGS.I_SNAP$_FGS_WIP_MVW ON FGS.FGS_WIP_MVW
(M_ROW$$)
LOGGING
TABLESPACE FGS_DATA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          128K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


-- Note: Index I_SNAP$_WIP_MASTER_MV will be created automatically 
--       by Oracle with the associated materialized view.  The following
--       script for this index is for informational purposes only.
CREATE UNIQUE INDEX FGS.I_SNAP$_WIP_MASTER_MV ON FGS.WIP_MASTER_MV
(M_ROW$$)
LOGGING
TABLESPACE FGS_DATA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE UNIQUE INDEX FGS.PF_RELS_ITEM_PK1 ON FGS.PF_RELS_ITEM_MV
(PF_RELS_NO, PROD_TYPE, P_CODE, PROD_BATCH, P_N_CODE)
LOGGING
TABLESPACE FGS_DATA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          3M
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE UNIQUE INDEX FGS.PK_CALENDER ON FGS.CALENDER
(CALCODE)
LOGGING
TABLESPACE FGS_DATA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE UNIQUE INDEX FGS.PK_DISP_ITEM ON FGS.DISP_ITEM
(DISP_SLNO, P_CODE, PROD_BATCH)
LOGGING
TABLESPACE FGS_DATA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE UNIQUE INDEX FGS.PK_DISP_MAIN ON FGS.DISP_MAIN
(DISP_SLNO)
LOGGING
TABLESPACE FGS_DATA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE UNIQUE INDEX FGS.PK_FGS_CS_RECV1 ON FGS.FGS_CS_RECV1
(INVNO, P_CODE, PROD_BATCH, PROD_TYPE)
LOGGING
TABLESPACE FGS_DATA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE UNIQUE INDEX FGS.PK_FGS_MON_OPN_STK ON FGS.FGS_MON_OPN_STK
(CALCODE, P_CODE)
LOGGING
TABLESPACE FGS_DATA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE UNIQUE INDEX FGS.PK_FGS_TRNS_PRDN ON FGS.FGS_TRNS_PRDN
(SL_NO, P_CODE)
LOGGING
TABLESPACE FGS_DATA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          2M
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE UNIQUE INDEX FGS.PK_PROD_STOK ON FGS.PROD_STOK
(P_CODE, PROD_BATCH)
LOGGING
TABLESPACE FGS_DATA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE UNIQUE INDEX FGS.PK_QA_SAMP_INFO ON FGS.QA_SAMP_INFO
(SAMP_SLNO)
LOGGING
TABLESPACE FGS_DATA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE UNIQUE INDEX FGS.PK_QA_SAMP_ITEM ON FGS.QA_SAMP_ITEM
(DISP_SLNO, P_CODE, PROD_BATCH, DISP_TO)
LOGGING
TABLESPACE FGS_DATA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE UNIQUE INDEX FGS.PK_QA_SAMP_MAIN ON FGS.QA_SAMP_MAIN
(DISP_SLNO)
LOGGING
TABLESPACE FGS_DATA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE UNIQUE INDEX FGS.PK_REC_ITEM ON FGS.REC_ITEM
(RECNO, P_CODE, PROD_BATCH)
LOGGING
TABLESPACE FGS_DATA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE UNIQUE INDEX FGS.PK_REC_MAIN ON FGS.REC_MAIN
(RECNO)
LOGGING
TABLESPACE FGS_DATA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE UNIQUE INDEX FGS.QA_RELS_ITEM_PK1 ON FGS.QA_RELS_ITEM_MV
(RELS_NO, PROD_TYPE, P_CODE, PROD_BATCH, P_N_CODE)
LOGGING
TABLESPACE FGS_DATA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          3M
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE UNIQUE INDEX FGS.QA_RELS_MAIN_PK ON FGS.QA_RELS_MAIN_MV
(RELS_NO)
LOGGING
TABLESPACE FGS_DATA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          2M
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE UNIQUE INDEX FGS.RELS_MAIN_PK ON FGS.PF_RELS_MAIN_MV
(PF_RELS_NO)
LOGGING
TABLESPACE FGS_DATA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          2M
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE UNIQUE INDEX FGS.RELS_MAIN_PK1 ON FGS.PF_RELS_MAIN_TEST
(PF_RELS_NO)
LOGGING
TABLESPACE FGS_DATA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          896K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


ALTER TABLE FGS.REC_MAIN ADD (
  CONSTRAINT PK_REC_MAIN
 PRIMARY KEY
 (RECNO)
    USING INDEX 
    TABLESPACE FGS_DATA
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                NEXT             1M
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                PCTINCREASE      0
               ));

ALTER TABLE FGS.REC_ITEM ADD (
  CONSTRAINT PK_REC_ITEM
 PRIMARY KEY
 (RECNO, P_CODE, PROD_BATCH)
    USING INDEX 
    TABLESPACE FGS_DATA
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                NEXT             1M
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                PCTINCREASE      0
               ));

ALTER TABLE FGS.QA_SAMP_MAIN ADD (
  CONSTRAINT PK_QA_SAMP_MAIN
 PRIMARY KEY
 (DISP_SLNO)
    USING INDEX 
    TABLESPACE FGS_DATA
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                NEXT             1M
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                PCTINCREASE      0
               ));

ALTER TABLE FGS.QA_SAMP_ITEM ADD (
  CONSTRAINT PK_QA_SAMP_ITEM
 PRIMARY KEY
 (DISP_SLNO, P_CODE, PROD_BATCH, DISP_TO)
    USING INDEX 
    TABLESPACE FGS_DATA
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                NEXT             1M
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                PCTINCREASE      0
               ));

ALTER TABLE FGS.QA_SAMP_INFO ADD (
  CONSTRAINT PK_QA_SAMP_INFO
 PRIMARY KEY
 (SAMP_SLNO)
    USING INDEX 
    TABLESPACE FGS_DATA
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                NEXT             1M
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                PCTINCREASE      0
               ));

ALTER TABLE FGS.QA_RELS_MAIN_MV ADD (
  CONSTRAINT QA_RELS_MAIN_PK
 PRIMARY KEY
 (RELS_NO)
    USING INDEX 
    TABLESPACE FGS_DATA
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          2M
                NEXT             1M
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                PCTINCREASE      0
               ));

ALTER TABLE FGS.QA_RELS_ITEM_MV ADD (
  CONSTRAINT QA_RELS_ITEM_PK1
 PRIMARY KEY
 (RELS_NO, PROD_TYPE, P_CODE, PROD_BATCH, P_N_CODE)
    USING INDEX 
    TABLESPACE FGS_DATA
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          3M
                NEXT             1M
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                PCTINCREASE      0
               ));

ALTER TABLE FGS.PROD_STOK ADD (
  CONSTRAINT PK_PROD_STOK
 PRIMARY KEY
 (P_CODE, PROD_BATCH)
    USING INDEX 
    TABLESPACE FGS_DATA
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                NEXT             1M
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                PCTINCREASE      0
               ));

ALTER TABLE FGS.PF_RELS_MAIN_TEST ADD (
  CONSTRAINT RELS_MAIN_PK1
 PRIMARY KEY
 (PF_RELS_NO)
    USING INDEX 
    TABLESPACE FGS_DATA
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          896K
                NEXT             1M
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                PCTINCREASE      0
               ));

ALTER TABLE FGS.PF_RELS_MAIN_MV ADD (
  CONSTRAINT RELS_MAIN_PK
 PRIMARY KEY
 (PF_RELS_NO)
    USING INDEX 
    TABLESPACE FGS_DATA
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          2M
                NEXT             1M
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                PCTINCREASE      0
               ));

ALTER TABLE FGS.PF_RELS_ITEM_MV ADD (
  CONSTRAINT PF_RELS_ITEM_PK1
 PRIMARY KEY
 (PF_RELS_NO, PROD_TYPE, P_CODE, PROD_BATCH, P_N_CODE)
    USING INDEX 
    TABLESPACE FGS_DATA
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          3M
                NEXT             1M
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                PCTINCREASE      0
               ));

ALTER TABLE FGS.MAT_COMMENTS ADD (
  PRIMARY KEY
 (OBJECT_NAME)
    USING INDEX 
    TABLESPACE FGS_DATA
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                NEXT             1M
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                PCTINCREASE      0
               ));

ALTER TABLE FGS.FGS_TRNS_PRDN ADD (
  CONSTRAINT PK_FGS_TRNS_PRDN
 PRIMARY KEY
 (SL_NO, P_CODE)
    USING INDEX 
    TABLESPACE FGS_DATA
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          2M
                NEXT             1M
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                PCTINCREASE      0
               ));

ALTER TABLE FGS.FGS_MON_OPN_STK ADD (
  CONSTRAINT PK_FGS_MON_OPN_STK
 PRIMARY KEY
 (CALCODE, P_CODE)
    USING INDEX 
    TABLESPACE FGS_DATA
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                NEXT             1M
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                PCTINCREASE      0
               ));

ALTER TABLE FGS.FGS_CS_RECV1 ADD (
  CONSTRAINT PK_FGS_CS_RECV1
 PRIMARY KEY
 (INVNO, P_CODE, PROD_BATCH, PROD_TYPE)
    USING INDEX 
    TABLESPACE FGS_DATA
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                NEXT             1M
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                PCTINCREASE      0
               ));

ALTER TABLE FGS.DISP_MAIN ADD (
  CONSTRAINT PK_DISP_MAIN
 PRIMARY KEY
 (DISP_SLNO)
    USING INDEX 
    TABLESPACE FGS_DATA
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                NEXT             1M
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                PCTINCREASE      0
               ));

ALTER TABLE FGS.DISP_ITEM ADD (
  CONSTRAINT PK_DISP_ITEM
 PRIMARY KEY
 (DISP_SLNO, P_CODE, PROD_BATCH)
    USING INDEX 
    TABLESPACE FGS_DATA
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                NEXT             1M
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                PCTINCREASE      0
               ));

ALTER TABLE FGS.CALENDER ADD (
  CONSTRAINT PK_CALENDER
 PRIMARY KEY
 (CALCODE)
    USING INDEX 
    TABLESPACE FGS_DATA
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                NEXT             1M
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                PCTINCREASE      0
               ));

ALTER TABLE FGS.REC_ITEM ADD (
  CONSTRAINT FK_REC_ITEM 
 FOREIGN KEY (RECNO) 
 REFERENCES FGS.REC_MAIN (RECNO));

ALTER TABLE FGS.QA_SAMP_ITEM ADD (
  CONSTRAINT FK_QA_SAMP_ITEM 
 FOREIGN KEY (DISP_SLNO) 
 REFERENCES FGS.QA_SAMP_MAIN (DISP_SLNO));

ALTER TABLE FGS.DISP_ITEM ADD (
  CONSTRAINT FK_DISP_ITEM 
 FOREIGN KEY (DISP_SLNO) 
 REFERENCES FGS.DISP_MAIN (DISP_SLNO));

GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON FGS.PF_RELS_ITEM_MV TO NPL;

GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON FGS.PF_RELS_MAIN_MV TO NPL;

GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON FGS.QA_RELS_ITEM_MV TO NPL;

GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON FGS.QA_RELS_MAIN_MV TO NPL;

GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON FGS.PF_RELS_ITEM_MV TO WHRP;

GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON FGS.PF_RELS_MAIN_MV TO WHRP;

GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON FGS.QA_RELS_ITEM_MV TO WHRP;

GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON FGS.QA_RELS_MAIN_MV TO WHRP;

