ALTER TABLE NPLGRA.EPF_CONTRI_MST
 DROP PRIMARY KEY CASCADE;

DROP TABLE NPLGRA.EPF_CONTRI_MST CASCADE CONSTRAINTS;

CREATE TABLE NPLGRA.EPF_CONTRI_MST
(
  EMP_CODE   VARCHAR2(5 BYTE),
  MNYR_CON   DATE,
  MEM_CONT   NUMBER(10,2),
  COM_CONT   NUMBER(10,2),
  IS_JV_GEN  VARCHAR2(1 BYTE),
  VC_NO      VARCHAR2(12 BYTE),
  USER_ID    VARCHAR2(5 BYTE),
  ENTER_DT   DATE
)
TABLESPACE NPLEPF_DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


ALTER TABLE NPLGRA.EPF_EMP_FINAL_PAY_MST
 DROP PRIMARY KEY CASCADE;

DROP TABLE NPLGRA.EPF_EMP_FINAL_PAY_MST CASCADE CONSTRAINTS;

CREATE TABLE NPLGRA.EPF_EMP_FINAL_PAY_MST
(
  EMP_CODE       VARCHAR2(5 BYTE),
  VC_NO          VARCHAR2(15 BYTE),
  IS_VC          VARCHAR2(1 BYTE),
  IS_APP         VARCHAR2(1 BYTE),
  APP_DT         DATE,
  PAY_DECISION   VARCHAR2(5 BYTE),
  NOTE           VARCHAR2(250 BYTE),
  PF_STATUS      VARCHAR2(100 BYTE),
  PF_START_DT    DATE,
  PF_LENGTH      VARCHAR2(100 BYTE),
  MEMBER_STATUS  VARCHAR2(50 BYTE),
  AC_CHEQUE      NUMBER(10,2),
  CASH_CHEQUE    NUMBER(10,2),
  CASH           NUMBER(10,2),
  EDIT_BY        VARCHAR2(5 BYTE),
  EDIT_DT        DATE,
  USER_ID        VARCHAR2(5 BYTE),
  ENTER_DT       DATE
)
TABLESPACE NPLEPF_DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


ALTER TABLE NPLGRA.EPF_EMP_PROFIT_DIST
 DROP PRIMARY KEY CASCADE;

DROP TABLE NPLGRA.EPF_EMP_PROFIT_DIST CASCADE CONSTRAINTS;

CREATE TABLE NPLGRA.EPF_EMP_PROFIT_DIST
(
  PF_ID         VARCHAR2(5 BYTE),
  MNYR          DATE,
  MEM_CON_AMNT  NUMBER(12,2),
  COM_CON_AMNT  NUMBER(12,2),
  NET_AMNT      NUMBER(12,2),
  PCT_CONTRI    NUMBER(12,4),
  EMP_PROFIT    NUMBER(12,4),
  ENTER_DT      DATE,
  USER_ID       VARCHAR2(5 BYTE)
)
TABLESPACE NPLEPF_DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


ALTER TABLE NPLGRA.EPF_LOAN_ADJUST_UPD
 DROP PRIMARY KEY CASCADE;

DROP TABLE NPLGRA.EPF_LOAN_ADJUST_UPD CASCADE CONSTRAINTS;

CREATE TABLE NPLGRA.EPF_LOAN_ADJUST_UPD
(
  EMP_CODE     VARCHAR2(5 BYTE),
  MNYR         DATE,
  PF_ADV_LOAN  NUMBER(20),
  PRINCIPAL    NUMBER(20),
  INTEREST     NUMBER(20),
  VC_STAT      VARCHAR2(5 BYTE),
  ENTER_DT     DATE,
  USER_ID      VARCHAR2(20 BYTE),
  VC_NO        VARCHAR2(12 BYTE)
)
TABLESPACE NPLEPF_DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          128K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


ALTER TABLE NPLGRA.EPF_MEMBER_ENROL_MST
 DROP PRIMARY KEY CASCADE;

DROP TABLE NPLGRA.EPF_MEMBER_ENROL_MST CASCADE CONSTRAINTS;

CREATE TABLE NPLGRA.EPF_MEMBER_ENROL_MST
(
  EMP_CODE     VARCHAR2(5 BYTE),
  PF_START_DT  DATE,
  PF_STATUS    VARCHAR2(2 BYTE),
  ENTER_DT     DATE,
  USER_ID      VARCHAR2(5 BYTE),
  INACTIVE_DT  DATE
)
TABLESPACE NPLEPF_DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          128K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


DROP TABLE NPLGRA.EPF_MEMBER_ENROL_MST_TEMP CASCADE CONSTRAINTS;

CREATE TABLE NPLGRA.EPF_MEMBER_ENROL_MST_TEMP
(
  EMP_CODE     VARCHAR2(5 BYTE),
  PF_START_DT  DATE,
  PF_STATUS    VARCHAR2(2 BYTE),
  ENTER_DT     DATE,
  USER_ID      VARCHAR2(5 BYTE)
)
TABLESPACE NPLEPF_DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


ALTER TABLE NPLGRA.EPF_MEM_REG_UPD
 DROP PRIMARY KEY CASCADE;

DROP TABLE NPLGRA.EPF_MEM_REG_UPD CASCADE CONSTRAINTS;

CREATE TABLE NPLGRA.EPF_MEM_REG_UPD
(
  EMP_CODE       VARCHAR2(5 BYTE),
  MNYR           DATE,
  VC_NO          VARCHAR2(12 BYTE),
  VC_DATE        DATE,
  NIS_DATE       DATE,
  COM_CONT_AMNT  NUMBER,
  MEM_CONT_AMNT  NUMBER,
  PROFIT_AMNT    NUMBER,
  VC_STAT        VARCHAR2(5 BYTE),
  USER_ID        VARCHAR2(20 BYTE),
  ENTER_DT       DATE
)
TABLESPACE NPLEPF_DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


ALTER TABLE NPLGRA.EPF_NOMINEE
 DROP PRIMARY KEY CASCADE;

DROP TABLE NPLGRA.EPF_NOMINEE CASCADE CONSTRAINTS;

CREATE TABLE NPLGRA.EPF_NOMINEE
(
  EMP_CODE     VARCHAR2(5 BYTE),
  NOM_TYPE     VARCHAR2(2 BYTE),
  NOM_NAME     VARCHAR2(75 BYTE),
  NOM_ADD      VARCHAR2(120 BYTE),
  RELA_TO_NOM  VARCHAR2(20 BYTE),
  SHARE_PCT    NUMBER(5),
  NOM_NID      VARCHAR2(17 BYTE),
  NOMINEE_PIC  BLOB,
  ENTER_DT     DATE,
  USER_ID      VARCHAR2(5 BYTE),
  NOM_PIC_B    BLOB
)
TABLESPACE NPLEPF_DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
LOB (NOM_PIC_B) STORE AS 
      ( TABLESPACE  NPLEPF_DATA 
        ENABLE      STORAGE IN ROW
        CHUNK       8192
        PCTVERSION  10
        NOCACHE
        INDEX       (
          TABLESPACE NPLEPF_DATA
          STORAGE    (
                      INITIAL          64K
                      NEXT             1
                      MINEXTENTS       1
                      MAXEXTENTS       UNLIMITED
                      PCTINCREASE      0
                      BUFFER_POOL      DEFAULT
                     ))
        STORAGE    (
                    INITIAL          64K
                    NEXT             1M
                    MINEXTENTS       1
                    MAXEXTENTS       UNLIMITED
                    PCTINCREASE      0
                    BUFFER_POOL      DEFAULT
                   )
      )
  LOB (NOMINEE_PIC) STORE AS 
      ( TABLESPACE  NPLEPF_DATA 
        ENABLE      STORAGE IN ROW
        CHUNK       8192
        PCTVERSION  10
        NOCACHE
        INDEX       (
          TABLESPACE NPLEPF_DATA
          STORAGE    (
                      INITIAL          64K
                      NEXT             1
                      MINEXTENTS       1
                      MAXEXTENTS       UNLIMITED
                      PCTINCREASE      0
                      BUFFER_POOL      DEFAULT
                     ))
        STORAGE    (
                    INITIAL          64K
                    NEXT             1M
                    MINEXTENTS       1
                    MAXEXTENTS       UNLIMITED
                    PCTINCREASE      0
                    BUFFER_POOL      DEFAULT
                   )
      )
NOCACHE
NOPARALLEL
MONITORING;


ALTER TABLE NPLGRA.GL_BANK_ACNT
 DROP PRIMARY KEY CASCADE;

DROP TABLE NPLGRA.GL_BANK_ACNT CASCADE CONSTRAINTS;

CREATE TABLE NPLGRA.GL_BANK_ACNT
(
  ACNT_SLNO    VARCHAR2(4 BYTE)                 NOT NULL,
  ACNT_NO      VARCHAR2(20 BYTE)                NOT NULL,
  BANK_CODE    VARCHAR2(3 BYTE)                 NOT NULL,
  BRANCH_CODE  VARCHAR2(3 BYTE)                 NOT NULL,
  ACNT_TCODE   VARCHAR2(3 BYTE)                 NOT NULL,
  USER_ID      VARCHAR2(10 BYTE),
  ENTER_DT     DATE,
  DIST_CODE    VARCHAR2(3 BYTE),
  OP_POINT     VARCHAR2(5 BYTE)
)
TABLESPACE NPLEPF_DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


ALTER TABLE NPLGRA.GL_BANK_ACNT_FACI_TYPE
 DROP PRIMARY KEY CASCADE;

DROP TABLE NPLGRA.GL_BANK_ACNT_FACI_TYPE CASCADE CONSTRAINTS;

CREATE TABLE NPLGRA.GL_BANK_ACNT_FACI_TYPE
(
  ACNT_FCODE  VARCHAR2(3 BYTE)                  NOT NULL,
  ACNT_FDESC  VARCHAR2(50 BYTE)
)
TABLESPACE NPLEPF_DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


ALTER TABLE NPLGRA.GL_BANK_ACNT_TYPE
 DROP PRIMARY KEY CASCADE;

DROP TABLE NPLGRA.GL_BANK_ACNT_TYPE CASCADE CONSTRAINTS;

CREATE TABLE NPLGRA.GL_BANK_ACNT_TYPE
(
  ACNT_TCODE  VARCHAR2(3 BYTE),
  ACNT_TDESC  VARCHAR2(50 BYTE)
)
TABLESPACE NPLEPF_DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


ALTER TABLE NPLGRA.GL_BANK_COA_SETUP
 DROP PRIMARY KEY CASCADE;

DROP TABLE NPLGRA.GL_BANK_COA_SETUP CASCADE CONSTRAINTS;

CREATE TABLE NPLGRA.GL_BANK_COA_SETUP
(
  ACNT_SLNO            VARCHAR2(4 BYTE)         NOT NULL,
  COA_CODE             VARCHAR2(20 BYTE),
  ACNT_FCODE           VARCHAR2(3 BYTE),
  CREDIT_LIMIT         NUMBER(20,2),
  USER_ID              VARCHAR2(10 BYTE),
  ENTER_DT             DATE,
  CREDIT_DAYS_LIMIT    NUMBER(4),
  INTEREST_PCT         NUMBER(10,2),
  IS_LOC_SUPP_PAYMENT  VARCHAR2(1 BYTE),
  IS_LC_OPENING        VARCHAR2(1 BYTE),
  MAIN_BANK_ACNT_COA   VARCHAR2(20 BYTE)
)
TABLESPACE NPLEPF_DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


DROP TABLE NPLGRA.GL_BS_STMT_RPT_GTEMP CASCADE CONSTRAINTS;

CREATE TABLE NPLGRA.GL_BS_STMT_RPT_GTEMP
(
  PSLNO       NUMBER,
  SLNO        VARCHAR2(2 BYTE),
  HEAD        VARCHAR2(50 BYTE),
  DATE_FROM   DATE,
  DATE_TO     DATE,
  OPEN_AMT    NUMBER(25,2),
  DR_AMT      NUMBER(25,2),
  CR_AMT      NUMBER(25,2),
  TOT_AMT     NUMBER(25,2),
  GROUP_HEAD  VARCHAR2(10 BYTE),
  IS_BOLD     VARCHAR2(1 BYTE),
  COA_TYPE    VARCHAR2(1 BYTE)
)
TABLESPACE NPLEPF_DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


DROP TABLE NPLGRA.GL_BS_STMT_SETUP_V1 CASCADE CONSTRAINTS;

CREATE TABLE NPLGRA.GL_BS_STMT_SETUP_V1
(
  PRINT_SLNO       NUMBER(4),
  SLNO             VARCHAR2(2 BYTE),
  HEAD             VARCHAR2(50 BYTE),
  IS_BOLD          VARCHAR2(1 BYTE),
  IS_RC_GL         VARCHAR2(4 BYTE),
  COA_CODE         VARCHAR2(8 BYTE),
  RC_CODE          VARCHAR2(4 BYTE),
  CALCULATION      VARCHAR2(50 BYTE),
  GROUP_HEAD       VARCHAR2(10 BYTE),
  ORDER_BY         NUMBER(3),
  COA_PARENT_CODE  VARCHAR2(8 BYTE),
  COA_TYPE         VARCHAR2(1 BYTE)
)
TABLESPACE NPLEPF_DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


ALTER TABLE NPLGRA.GL_CHEQ_MAIN
 DROP PRIMARY KEY CASCADE;

DROP TABLE NPLGRA.GL_CHEQ_MAIN CASCADE CONSTRAINTS;

CREATE TABLE NPLGRA.GL_CHEQ_MAIN
(
  SLNO         NUMBER(6),
  CHEQ_REF_NO  VARCHAR2(20 BYTE),
  BANK_CODE    VARCHAR2(3 BYTE),
  BRANCH_CODE  VARCHAR2(3 BYTE),
  ACNT_NO      VARCHAR2(20 BYTE),
  GL_CODE      VARCHAR2(20 BYTE),
  RECV_DATE    DATE,
  CHEQP_FROM   NUMBER(10),
  CHEQP_TO     NUMBER(10),
  NOF_CHEQP    NUMBER(3),
  USER_ID      VARCHAR2(9 BYTE),
  ENTER_DT     DATE
)
TABLESPACE NPLEPF_DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


ALTER TABLE NPLGRA.GL_COA
 DROP PRIMARY KEY CASCADE;

DROP TABLE NPLGRA.GL_COA CASCADE CONSTRAINTS;

CREATE TABLE NPLGRA.GL_COA
(
  COA_CODE           VARCHAR2(20 BYTE)          NOT NULL,
  COA_DESC_LONG      VARCHAR2(50 BYTE),
  COA_DESC_SHORT     VARCHAR2(35 BYTE),
  COA_MAIN_GRP       VARCHAR2(1 BYTE),
  COA_ACCOUNT_TYPE   VARCHAR2(1 BYTE),
  COA_PARENT_CODE    VARCHAR2(20 BYTE),
  COA_POS_IN_REPORT  NUMBER(3),
  COA_DEF_BAL_TYPE   VARCHAR2(1 BYTE),
  IS_RC_DRIVEN       VARCHAR2(1 BYTE),
  IS_VEND_DRIVEN     VARCHAR2(1 BYTE),
  IS_BUDGET          VARCHAR2(1 BYTE),
  IS_ADVANCE_REG     VARCHAR2(1 BYTE),
  IS_ADVANCE_BLOCK   VARCHAR2(1 BYTE)
)
TABLESPACE NPLEPF_DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


ALTER TABLE NPLGRA.GL_COA_CODE_LEVEL
 DROP PRIMARY KEY CASCADE;

DROP TABLE NPLGRA.GL_COA_CODE_LEVEL CASCADE CONSTRAINTS;

CREATE TABLE NPLGRA.GL_COA_CODE_LEVEL
(
  LEVEL_COMP_ID  VARCHAR2(3 BYTE)               NOT NULL,
  LEVEL_SLNO     NUMBER(1)                      NOT NULL,
  LEVEL_DESC     VARCHAR2(50 BYTE),
  LEVEL_LENGTH   NUMBER(2)
)
TABLESPACE NPLEPF_DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


ALTER TABLE NPLGRA.GL_COA_HISTORY
 DROP PRIMARY KEY CASCADE;

DROP TABLE NPLGRA.GL_COA_HISTORY CASCADE CONSTRAINTS;

CREATE TABLE NPLGRA.GL_COA_HISTORY
(
  COA_CODE           VARCHAR2(20 BYTE)          NOT NULL,
  COA_DESC_LONG      VARCHAR2(50 BYTE),
  COA_DESC_SHORT     VARCHAR2(30 BYTE),
  COA_MAIN_GRP       VARCHAR2(1 BYTE),
  COA_ACCOUNT_TYPE   VARCHAR2(1 BYTE),
  COA_PARENT_CODE    VARCHAR2(20 BYTE),
  COA_POS_IN_REPORT  NUMBER(3),
  COA_DEF_BAL_TYPE   VARCHAR2(1 BYTE),
  IS_RC_DRIVEN       VARCHAR2(1 BYTE),
  IS_VEND_DRIVEN     VARCHAR2(1 BYTE),
  IS_BUDGET          VARCHAR2(1 BYTE),
  IS_ADVANCE_REG     VARCHAR2(1 BYTE),
  IS_ADVANCE_BLOCK   VARCHAR2(1 BYTE),
  USER_ID            VARCHAR2(9 BYTE),
  ENTER_DT           DATE,
  SLNO               NUMBER(4)
)
TABLESPACE NPLEPF_DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


DROP TABLE NPLGRA.GL_COA_RPT_TEMP CASCADE CONSTRAINTS;

CREATE TABLE NPLGRA.GL_COA_RPT_TEMP
(
  COA_CODE  VARCHAR2(10 BYTE)
)
TABLESPACE NPLEPF_DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


ALTER TABLE NPLGRA.GL_COMPANY
 DROP PRIMARY KEY CASCADE;

DROP TABLE NPLGRA.GL_COMPANY CASCADE CONSTRAINTS;

CREATE TABLE NPLGRA.GL_COMPANY
(
  COMP_ID                     VARCHAR2(3 BYTE)  NOT NULL,
  COMP_NAME                   VARCHAR2(50 BYTE),
  COMP_ADD1                   VARCHAR2(40 BYTE),
  COMP_ADD2                   VARCHAR2(30 BYTE),
  COMP_ADD3                   VARCHAR2(25 BYTE),
  COMP_ADD4                   VARCHAR2(25 BYTE),
  COMP_PHONE_NO1              VARCHAR2(20 BYTE),
  COMP_PHONE_NO2              VARCHAR2(20 BYTE),
  COMP_FAX_NO                 VARCHAR2(20 BYTE),
  COMP_EMAIL                  VARCHAR2(25 BYTE),
  COMP_WEBSITE                VARCHAR2(25 BYTE),
  COMP_DEF_CURRENCY           VARCHAR2(5 BYTE),
  COMP_COA_CODE_TOTAL_LENGTH  NUMBER(2)
)
TABLESPACE NPLEPF_DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


ALTER TABLE NPLGRA.GL_CURRENCY
 DROP PRIMARY KEY CASCADE;

DROP TABLE NPLGRA.GL_CURRENCY CASCADE CONSTRAINTS;

CREATE TABLE NPLGRA.GL_CURRENCY
(
  CUR_CODE        VARCHAR2(4 BYTE)              NOT NULL,
  CUR_DESC        VARCHAR2(50 BYTE),
  CUR_CONV_RATIO  NUMBER(10,4),
  CUR_STATUS      VARCHAR2(1 BYTE),
  CUR_VALID_FROM  DATE,
  CUR_VALID_TO    DATE
)
TABLESPACE NPLEPF_DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


DROP TABLE NPLGRA.GL_INCOME_STMT_RPT_GTEMP CASCADE CONSTRAINTS;

CREATE TABLE NPLGRA.GL_INCOME_STMT_RPT_GTEMP
(
  PSLNO       NUMBER,
  SLNO        VARCHAR2(2 BYTE),
  HEAD        VARCHAR2(50 BYTE),
  DATE_FROM   DATE,
  DATE_TO     DATE,
  TOT_AMT     NUMBER(25,2),
  GROUP_HEAD  VARCHAR2(10 BYTE),
  IS_BOLD     VARCHAR2(1 BYTE)
)
TABLESPACE NPLEPF_DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


DROP TABLE NPLGRA.GL_INCOME_STMT_RPT_GTEMP_TEMP CASCADE CONSTRAINTS;

CREATE TABLE NPLGRA.GL_INCOME_STMT_RPT_GTEMP_TEMP
(
  PSLNO       NUMBER,
  SLNO        VARCHAR2(2 BYTE),
  HEAD        VARCHAR2(50 BYTE),
  DATE_FROM   DATE,
  DATE_TO     DATE,
  TOT_AMT     NUMBER(25,2),
  GROUP_HEAD  VARCHAR2(10 BYTE),
  IS_BOLD     VARCHAR2(1 BYTE),
  PCT         NUMBER
)
TABLESPACE NPLEPF_DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


DROP TABLE NPLGRA.GL_INCOME_STMT_SETUP CASCADE CONSTRAINTS;

CREATE TABLE NPLGRA.GL_INCOME_STMT_SETUP
(
  PRINT_SLNO      NUMBER(4),
  SLNO            VARCHAR2(2 BYTE),
  HEAD            VARCHAR2(50 BYTE),
  IS_BOLD         VARCHAR2(1 BYTE),
  IS_RC_GL        VARCHAR2(4 BYTE),
  COA_CODE        VARCHAR2(8 BYTE),
  RC_CODE         VARCHAR2(4 BYTE),
  CALCULATION     VARCHAR2(50 BYTE),
  GROUP_HEAD      VARCHAR2(10 BYTE),
  SUB_HEAD        VARCHAR2(50 BYTE),
  SUB_GROUP_HEAD  VARCHAR2(10 BYTE),
  SUB_RC_GL       VARCHAR2(4 BYTE)
)
TABLESPACE NPLEPF_DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


DROP TABLE NPLGRA.GL_MULTI_REPORT CASCADE CONSTRAINTS;

CREATE TABLE NPLGRA.GL_MULTI_REPORT
(
  VC_NO         VARCHAR2(12 BYTE),
  VC_DATE       DATE,
  ENTERED_DATE  DATE,
  VJ_CODE       VARCHAR2(2 BYTE),
  ENTERED_BY    VARCHAR2(10 BYTE),
  COA_CODE      VARCHAR2(20 BYTE),
  RC_CODE       VARCHAR2(4 BYTE),
  REFERENCE     VARCHAR2(50 BYTE),
  DR_AMOUNT     NUMBER(30,2),
  CR_AMOUNT     NUMBER(30,2),
  DATE_FROM     DATE,
  DATE_TO       DATE
)
TABLESPACE NPLEPF_DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


DROP TABLE NPLGRA.GL_MULTI_REPORT_TEMP CASCADE CONSTRAINTS;

CREATE TABLE NPLGRA.GL_MULTI_REPORT_TEMP
(
  VC_NO         VARCHAR2(12 BYTE),
  VC_DATE       DATE,
  ENTERED_DATE  DATE,
  VJ_CODE       VARCHAR2(2 BYTE),
  ENTERED_BY    VARCHAR2(10 BYTE),
  COA_CODE      VARCHAR2(20 BYTE),
  RC_CODE       VARCHAR2(4 BYTE),
  REFERENCE     VARCHAR2(100 BYTE),
  DR_AMOUNT     NUMBER(30,2),
  CR_AMOUNT     NUMBER(30,2)
)
TABLESPACE NPLEPF_DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


ALTER TABLE NPLGRA.GL_PAYEE
 DROP PRIMARY KEY CASCADE;

DROP TABLE NPLGRA.GL_PAYEE CASCADE CONSTRAINTS;

CREATE TABLE NPLGRA.GL_PAYEE
(
  PAYEE_CODE      VARCHAR2(10 BYTE),
  PAYEE_DESC      VARCHAR2(100 BYTE),
  PAYEE_TYPE      VARCHAR2(1 BYTE),
  PAYEE_OPEN_BAL  NUMBER(16,2),
  PAYEE_REF_CODE  VARCHAR2(10 BYTE)
)
TABLESPACE NPLEPF_DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          320K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


ALTER TABLE NPLGRA.GL_PAYEE_TYPE
 DROP PRIMARY KEY CASCADE;

DROP TABLE NPLGRA.GL_PAYEE_TYPE CASCADE CONSTRAINTS;

CREATE TABLE NPLGRA.GL_PAYEE_TYPE
(
  SLNO             NUMBER(3),
  PAYEE_TYPE_DESC  VARCHAR2(100 BYTE),
  PREFIX           VARCHAR2(1 BYTE)
)
TABLESPACE NPLEPF_DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


DROP TABLE NPLGRA.GL_PAYEE_WISE_OPEN_BAL CASCADE CONSTRAINTS;

CREATE TABLE NPLGRA.GL_PAYEE_WISE_OPEN_BAL
(
  PAYEE_CODE  VARCHAR2(10 BYTE),
  OPEN_BAL    NUMBER,
  COA_CODE    VARCHAR2(10 BYTE),
  DATE_FROM   DATE,
  DATE_TO     DATE
)
TABLESPACE NPLEPF_DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


ALTER TABLE NPLGRA.GL_PAY_MODE
 DROP PRIMARY KEY CASCADE;

DROP TABLE NPLGRA.GL_PAY_MODE CASCADE CONSTRAINTS;

CREATE TABLE NPLGRA.GL_PAY_MODE
(
  PM_CODE     VARCHAR2(2 BYTE)                  NOT NULL,
  PM_DESC     VARCHAR2(30 BYTE),
  PREFIX      VARCHAR2(2 BYTE),
  REF_NO      VARCHAR2(20 BYTE),
  REF_SLNO    VARCHAR2(4 BYTE),
  USER_ID     VARCHAR2(9 BYTE),
  ENTER_DT    DATE,
  TRANS_TYPE  VARCHAR2(1 BYTE)
)
TABLESPACE NPLEPF_DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


ALTER TABLE NPLGRA.GL_PERIOD
 DROP PRIMARY KEY CASCADE;

DROP TABLE NPLGRA.GL_PERIOD CASCADE CONSTRAINTS;

CREATE TABLE NPLGRA.GL_PERIOD
(
  CAL_CODE         VARCHAR2(6 BYTE)             NOT NULL,
  CAL_DATE_FROM    DATE,
  CAL_DATE_TO      DATE,
  CLOSED           VARCHAR2(1 BYTE),
  IS_DEPRECIATION  VARCHAR2(1 BYTE),
  FISCAL_YEAR      VARCHAR2(4 BYTE),
  MON_NAME         VARCHAR2(30 BYTE)
)
TABLESPACE NPLEPF_DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


ALTER TABLE NPLGRA.GL_RC
 DROP PRIMARY KEY CASCADE;

DROP TABLE NPLGRA.GL_RC CASCADE CONSTRAINTS;

CREATE TABLE NPLGRA.GL_RC
(
  RC_CODE           VARCHAR2(4 BYTE)            NOT NULL,
  RC_DESC_LONG      VARCHAR2(75 BYTE),
  RC_DESC_SHORT     VARCHAR2(50 BYTE),
  RC_PARENT         VARCHAR2(4 BYTE),
  RC_POS_IN_REPORT  NUMBER(3),
  RC_TRANS_TYPE     VARCHAR2(1 BYTE)
)
TABLESPACE NPLEPF_DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


ALTER TABLE NPLGRA.GL_RC_LIST
 DROP PRIMARY KEY CASCADE;

DROP TABLE NPLGRA.GL_RC_LIST CASCADE CONSTRAINTS;

CREATE TABLE NPLGRA.GL_RC_LIST
(
  COA_CODE  VARCHAR2(20 BYTE)                   NOT NULL,
  RC_CODE   VARCHAR2(4 BYTE)                    NOT NULL
)
TABLESPACE NPLEPF_DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


DROP TABLE NPLGRA.GL_RC_RPT_TEMP CASCADE CONSTRAINTS;

CREATE TABLE NPLGRA.GL_RC_RPT_TEMP
(
  RC_CODE  VARCHAR2(4 BYTE)
)
TABLESPACE NPLEPF_DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


ALTER TABLE NPLGRA.GL_USER_VJ_PREF
 DROP PRIMARY KEY CASCADE;

DROP TABLE NPLGRA.GL_USER_VJ_PREF CASCADE CONSTRAINTS;

CREATE TABLE NPLGRA.GL_USER_VJ_PREF
(
  USER_ID  VARCHAR2(10 BYTE)                    NOT NULL,
  VJ_CODE  VARCHAR2(2 BYTE)                     NOT NULL,
  VJ_SLNO  NUMBER(2)
)
TABLESPACE NPLEPF_DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


ALTER TABLE NPLGRA.GL_VJ_TYPE
 DROP PRIMARY KEY CASCADE;

DROP TABLE NPLGRA.GL_VJ_TYPE CASCADE CONSTRAINTS;

CREATE TABLE NPLGRA.GL_VJ_TYPE
(
  VJ_CODE    VARCHAR2(2 BYTE)                   NOT NULL,
  VJ_DESC    VARCHAR2(50 BYTE),
  VJ_PREFIX  VARCHAR2(3 BYTE),
  VJ_PARENT  VARCHAR2(2 BYTE),
  IS_PAYEE   VARCHAR2(1 BYTE),
  IS_CHEQUE  VARCHAR2(1 BYTE)
)
TABLESPACE NPLEPF_DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


ALTER TABLE NPLGRA.GL_VOUCHER_DETAIL
 DROP PRIMARY KEY CASCADE;

DROP TABLE NPLGRA.GL_VOUCHER_DETAIL CASCADE CONSTRAINTS;

CREATE TABLE NPLGRA.GL_VOUCHER_DETAIL
(
  VC_NO               VARCHAR2(12 BYTE)         NOT NULL,
  COA_CODE            VARCHAR2(20 BYTE)         NOT NULL,
  RC_CODE             VARCHAR2(4 BYTE)          NOT NULL,
  VD_DESCRIPTION      VARCHAR2(1000 BYTE),
  VD_REFERENCE        VARCHAR2(50 BYTE),
  VD_UNPOSTED_DR_AMT  NUMBER(16,2),
  VD_UNPOSTED_CR_AMT  NUMBER(16,2),
  VD_ENTERED_DR_AMT   NUMBER(16,2),
  VD_ENTERED_CR_AMT   NUMBER(16,2),
  VD_POSTED_DR_AMT    NUMBER(16,2),
  VD_POSTED_CR_AMT    NUMBER(16,2),
  COA_SOURCE          VARCHAR2(1 BYTE),
  SUP_CODE            VARCHAR2(10 BYTE),
  SLNO                NUMBER(4)
)
TABLESPACE NPLEPF_DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          3M
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


DROP TABLE NPLGRA.GL_VOUCHER_DETAIL_TEMP CASCADE CONSTRAINTS;

CREATE TABLE NPLGRA.GL_VOUCHER_DETAIL_TEMP
(
  VC_NO               VARCHAR2(12 BYTE)         NOT NULL,
  COA_CODE            VARCHAR2(20 BYTE)         NOT NULL,
  RC_CODE             VARCHAR2(4 BYTE)          NOT NULL,
  VD_DESCRIPTION      VARCHAR2(1000 BYTE),
  VD_REFERENCE        VARCHAR2(50 BYTE),
  VD_UNPOSTED_DR_AMT  NUMBER(16,2),
  VD_UNPOSTED_CR_AMT  NUMBER(16,2),
  VD_ENTERED_DR_AMT   NUMBER(16,2),
  VD_ENTERED_CR_AMT   NUMBER(16,2),
  VD_POSTED_DR_AMT    NUMBER(16,2),
  VD_POSTED_CR_AMT    NUMBER(16,2),
  COA_SOURCE          VARCHAR2(1 BYTE),
  SUP_CODE            VARCHAR2(10 BYTE),
  SLNO                NUMBER(4)
)
TABLESPACE NPLEPF_DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


ALTER TABLE NPLGRA.GL_VOUCHER_MAIN
 DROP PRIMARY KEY CASCADE;

DROP TABLE NPLGRA.GL_VOUCHER_MAIN CASCADE CONSTRAINTS;

CREATE TABLE NPLGRA.GL_VOUCHER_MAIN
(
  VC_NO             VARCHAR2(12 BYTE)           NOT NULL,
  VC_DATE           DATE,
  VC_ENTERED        DATE,
  VJ_CODE           VARCHAR2(2 BYTE),
  VC_ENTERED_BY     VARCHAR2(10 BYTE),
  VC_POSTED_BY      VARCHAR2(10 BYTE),
  VC_RECEIVED_BY    VARCHAR2(10 BYTE),
  VC_PREPARED_BY    VARCHAR2(10 BYTE),
  VC_CHECKED_BY     VARCHAR2(10 BYTE),
  VC_APPROVED_BY    VARCHAR2(10 BYTE),
  VC_POSTED_DATE    DATE,
  CUR_CODE          VARCHAR2(4 BYTE),
  VC_CONV_RATE      NUMBER(10,4),
  VC_IS_POSTED      VARCHAR2(1 BYTE),
  PAYEE_CODE        VARCHAR2(10 BYTE),
  IS_CHEQUE         VARCHAR2(25 BYTE),
  PM_CODE           VARCHAR2(2 BYTE),
  VC_LETTER_REF_NO  VARCHAR2(25 BYTE),
  IS_SYSTEM         VARCHAR2(1 BYTE),
  PO_CLEA_DATE      DATE,
  VC_EDIT_BY        VARCHAR2(10 BYTE),
  VC_EDIT_DATE      DATE,
  VC_CAT            VARCHAR2(2 BYTE)
)
TABLESPACE NPLEPF_DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


DROP TABLE NPLGRA.GL_VOUCHER_MAIN_TEMP CASCADE CONSTRAINTS;

CREATE TABLE NPLGRA.GL_VOUCHER_MAIN_TEMP
(
  VC_NO             VARCHAR2(12 BYTE)           NOT NULL,
  VC_DATE           DATE,
  VC_ENTERED        DATE,
  VJ_CODE           VARCHAR2(2 BYTE),
  VC_ENTERED_BY     VARCHAR2(10 BYTE),
  VC_POSTED_BY      VARCHAR2(10 BYTE),
  VC_RECEIVED_BY    VARCHAR2(10 BYTE),
  VC_PREPARED_BY    VARCHAR2(10 BYTE),
  VC_CHECKED_BY     VARCHAR2(10 BYTE),
  VC_APPROVED_BY    VARCHAR2(10 BYTE),
  VC_POSTED_DATE    DATE,
  CUR_CODE          VARCHAR2(4 BYTE),
  VC_CONV_RATE      NUMBER(10,4),
  VC_IS_POSTED      VARCHAR2(1 BYTE),
  PAYEE_CODE        VARCHAR2(10 BYTE),
  IS_CHEQUE         VARCHAR2(25 BYTE),
  PM_CODE           VARCHAR2(2 BYTE),
  VC_LETTER_REF_NO  VARCHAR2(25 BYTE),
  IS_SYSTEM         VARCHAR2(1 BYTE),
  PO_CLEA_DATE      DATE,
  VC_EDIT_BY        VARCHAR2(10 BYTE),
  VC_EDIT_DATE      DATE,
  VC_CAT            VARCHAR2(2 BYTE)
)
TABLESPACE NPLEPF_DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


DROP TABLE NPLGRA.GL_WISE_DTL_RPT_TMP CASCADE CONSTRAINTS;

CREATE TABLE NPLGRA.GL_WISE_DTL_RPT_TMP
(
  DATE_FROM  DATE,
  DATE_TO    DATE,
  COA_CODE   VARCHAR2(12 BYTE),
  COA_DESC   VARCHAR2(100 BYTE),
  RC_FROM    VARCHAR2(4 BYTE),
  RC_TO      VARCHAR2(4 BYTE),
  DOC_STAT   VARCHAR2(1 BYTE),
  OPEN_BAL   NUMBER(20,2),
  VC_NO      VARCHAR2(11 BYTE),
  VC_DATE    DATE,
  VC_TYPE    VARCHAR2(100 BYTE),
  RC_CODE    VARCHAR2(4 BYTE),
  RC_DESC    VARCHAR2(100 BYTE),
  VC_DESC    VARCHAR2(500 BYTE),
  VC_DR_AMT  NUMBER(16,2),
  VC_CR_AMT  NUMBER(16,2),
  VC_REF     VARCHAR2(100 BYTE),
  VC_ENT_BY  VARCHAR2(100 BYTE),
  VC_ENT_DT  DATE
)
TABLESPACE NPLEPF_DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


DROP TABLE NPLGRA.GL_WISE_LEDGER_BOOK_RPT CASCADE CONSTRAINTS;

CREATE TABLE NPLGRA.GL_WISE_LEDGER_BOOK_RPT
(
  DATE_FROM       DATE,
  DATE_TO         DATE,
  VC_DATE         DATE,
  VC_NO           VARCHAR2(20 BYTE),
  COA_CODE        VARCHAR2(20 BYTE),
  RC_CODE         VARCHAR2(4 BYTE),
  VC_DESCRIPTION  VARCHAR2(1000 BYTE),
  VC_DR_AMT       NUMBER(30,2),
  VC_CR_AMT       NUMBER(30,2),
  VC_BALANCE      NUMBER(30,2),
  VC_OPEN_BAL     NUMBER(30,2),
  VC_CLOS_BAL     NUMBER(30,2),
  SLNO            NUMBER(10),
  IS_CHEQUE       VARCHAR2(25 BYTE),
  PAYEE_CODE      VARCHAR2(10 BYTE),
  SUP_OPEN_BAL    NUMBER
)
TABLESPACE NPLEPF_DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          320K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


DROP TABLE NPLGRA.GL_WISE_LEDGER_BOOK_SUMM_RPT CASCADE CONSTRAINTS;

CREATE TABLE NPLGRA.GL_WISE_LEDGER_BOOK_SUMM_RPT
(
  DATE_FROM     DATE,
  DATE_TO       DATE,
  COA_CODE      VARCHAR2(20 BYTE),
  PAYEE_CODE    VARCHAR2(10 BYTE),
  VC_OPEN_BAL   NUMBER(30,2),
  VC_DR_AMT     NUMBER(30,2),
  VC_CR_AMT     NUMBER(30,2),
  VC_BALANCE    NUMBER(30,2),
  VC_CLOS_BAL   NUMBER(30,2),
  SUP_OPEN_BAL  NUMBER
)
TABLESPACE NPLEPF_DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          192K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


DROP TABLE NPLGRA.PMIS_EPF_TEMP CASCADE CONSTRAINTS;

CREATE TABLE NPLGRA.PMIS_EPF_TEMP
(
  EMP_CODE     VARCHAR2(5 BYTE),
  PF_START_DT  DATE
)
TABLESPACE NPLEPF_DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          128K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


DROP TABLE NPLGRA.TRIAL_BAL_TMP CASCADE CONSTRAINTS;

CREATE TABLE NPLGRA.TRIAL_BAL_TMP
(
  PFROM        DATE,
  PTO          DATE,
  COA_FROM     VARCHAR2(12 BYTE),
  COA_TO       VARCHAR2(12 BYTE),
  RC_FROM      VARCHAR2(4 BYTE),
  RC_TO        VARCHAR2(4 BYTE),
  BAL_TYPE     VARCHAR2(1 BYTE),
  COA_CODE     VARCHAR2(12 BYTE),
  COA_DESC     VARCHAR2(100 BYTE),
  OPEN_BAL     NUMBER(20,2),
  TBAL_DR      NUMBER(20,2),
  TBAL_CR      NUMBER(20,2),
  TBAL         NUMBER(20,2),
  OPEN_BAL_DR  NUMBER,
  OPEN_BAL_CR  NUMBER,
  CUR_DR       NUMBER,
  CUR_CR       NUMBER
)
TABLESPACE NPLEPF_DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX NPLGRA.EMP_CODE_PK ON NPLGRA.EPF_LOAN_ADJUST_UPD
(EMP_CODE, MNYR)
LOGGING
TABLESPACE NPLEPF_DATA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE UNIQUE INDEX NPLGRA.EPF_CONTRI_MST_PK ON NPLGRA.EPF_CONTRI_MST
(EMP_CODE, MNYR_CON)
LOGGING
TABLESPACE NPLEPF_DATA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE UNIQUE INDEX NPLGRA.EPF_EMP_FINAL_PAY_MST_PK ON NPLGRA.EPF_EMP_FINAL_PAY_MST
(EMP_CODE)
LOGGING
TABLESPACE NPLEPF_DATA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE UNIQUE INDEX NPLGRA.EPF_EMP_PROFIT_DIST_PK ON NPLGRA.EPF_EMP_PROFIT_DIST
(PF_ID, MNYR)
LOGGING
TABLESPACE NPLEPF_DATA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE UNIQUE INDEX NPLGRA.EPF_MEMBER_ENROL_MST_PK ON NPLGRA.EPF_MEMBER_ENROL_MST
(EMP_CODE)
LOGGING
TABLESPACE NPLEPF_DATA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          128K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE UNIQUE INDEX NPLGRA.EPF_NOMINEE_PK ON NPLGRA.EPF_NOMINEE
(EMP_CODE, NOM_TYPE)
LOGGING
TABLESPACE NPLEPF_DATA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE UNIQUE INDEX NPLGRA.PK_GL_BANK_ACNT ON NPLGRA.GL_BANK_ACNT
(ACNT_SLNO)
LOGGING
TABLESPACE NPLEPF_DATA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE UNIQUE INDEX NPLGRA.PK_GL_BANK_ACNT_FACI_TYPE ON NPLGRA.GL_BANK_ACNT_FACI_TYPE
(ACNT_FCODE)
LOGGING
TABLESPACE NPLEPF_DATA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE UNIQUE INDEX NPLGRA.PK_GL_BANK_ACNT_TYPE ON NPLGRA.GL_BANK_ACNT_TYPE
(ACNT_TCODE)
LOGGING
TABLESPACE NPLEPF_DATA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE UNIQUE INDEX NPLGRA.PK_GL_BANK_COA_SETUP ON NPLGRA.GL_BANK_COA_SETUP
(ACNT_SLNO)
LOGGING
TABLESPACE NPLEPF_DATA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE UNIQUE INDEX NPLGRA.PK_GL_CHEQ_MAIN ON NPLGRA.GL_CHEQ_MAIN
(SLNO, CHEQ_REF_NO)
LOGGING
TABLESPACE NPLEPF_DATA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE UNIQUE INDEX NPLGRA.PK_GL_COA ON NPLGRA.GL_COA
(COA_CODE)
LOGGING
TABLESPACE NPLEPF_DATA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE UNIQUE INDEX NPLGRA.PK_GL_COA_CODE_LEVEL ON NPLGRA.GL_COA_CODE_LEVEL
(LEVEL_COMP_ID, LEVEL_SLNO)
LOGGING
TABLESPACE NPLEPF_DATA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE UNIQUE INDEX NPLGRA.PK_GL_COA_HISTORY ON NPLGRA.GL_COA_HISTORY
(SLNO)
LOGGING
TABLESPACE NPLEPF_DATA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE UNIQUE INDEX NPLGRA.PK_GL_COMPANY ON NPLGRA.GL_COMPANY
(COMP_ID)
LOGGING
TABLESPACE NPLEPF_DATA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE UNIQUE INDEX NPLGRA.PK_GL_CURRENCY ON NPLGRA.GL_CURRENCY
(CUR_CODE)
LOGGING
TABLESPACE NPLEPF_DATA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE UNIQUE INDEX NPLGRA.PK_GL_PAYEE ON NPLGRA.GL_PAYEE
(PAYEE_CODE)
LOGGING
TABLESPACE NPLEPF_DATA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          256K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE UNIQUE INDEX NPLGRA.PK_GL_PAYEE_TYPE ON NPLGRA.GL_PAYEE_TYPE
(SLNO)
LOGGING
TABLESPACE NPLEPF_DATA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE UNIQUE INDEX NPLGRA.PK_GL_PAY_MODE ON NPLGRA.GL_PAY_MODE
(PM_CODE)
LOGGING
TABLESPACE NPLEPF_DATA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE UNIQUE INDEX NPLGRA.PK_GL_PERIOD ON NPLGRA.GL_PERIOD
(CAL_CODE, CAL_DATE_FROM)
LOGGING
TABLESPACE NPLEPF_DATA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE UNIQUE INDEX NPLGRA.PK_GL_RC ON NPLGRA.GL_RC
(RC_CODE)
LOGGING
TABLESPACE NPLEPF_DATA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE UNIQUE INDEX NPLGRA.PK_GL_RC_LIST ON NPLGRA.GL_RC_LIST
(COA_CODE, RC_CODE)
LOGGING
TABLESPACE NPLEPF_DATA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE UNIQUE INDEX NPLGRA.PK_GL_USER_VJ_PREF ON NPLGRA.GL_USER_VJ_PREF
(USER_ID, VJ_CODE)
LOGGING
TABLESPACE NPLEPF_DATA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE UNIQUE INDEX NPLGRA.PK_GL_VJ_TYPE ON NPLGRA.GL_VJ_TYPE
(VJ_CODE)
LOGGING
TABLESPACE NPLEPF_DATA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE UNIQUE INDEX NPLGRA.PK_GL_VOUCHER_DETAIL ON NPLGRA.GL_VOUCHER_DETAIL
(VC_NO, COA_CODE, RC_CODE, SLNO)
LOGGING
TABLESPACE NPLEPF_DATA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          3M
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE UNIQUE INDEX NPLGRA.PK_GL_VOUCHER_MAIN ON NPLGRA.GL_VOUCHER_MAIN
(VC_NO)
LOGGING
TABLESPACE NPLEPF_DATA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


ALTER TABLE NPLGRA.EPF_EMP_FINAL_PAY_DTL
 DROP PRIMARY KEY CASCADE;

DROP TABLE NPLGRA.EPF_EMP_FINAL_PAY_DTL CASCADE CONSTRAINTS;

CREATE TABLE NPLGRA.EPF_EMP_FINAL_PAY_DTL
(
  EMP_CODE  VARCHAR2(5 BYTE),
  COA_CODE  VARCHAR2(25 BYTE),
  AMOUNT    NUMBER(10,2),
  COA_TYPE  VARCHAR2(1 BYTE),
  REMARKS   VARCHAR2(120 BYTE),
  USER_ID   VARCHAR2(5 BYTE),
  ENTER_DT  DATE
)
TABLESPACE NPLEPF_DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


ALTER TABLE NPLGRA.GL_CHEQ_DTL
 DROP PRIMARY KEY CASCADE;

DROP TABLE NPLGRA.GL_CHEQ_DTL CASCADE CONSTRAINTS;

CREATE TABLE NPLGRA.GL_CHEQ_DTL
(
  SLNO                 NUMBER(6),
  CHEQ_REF_NO          VARCHAR2(20 BYTE),
  CHEQP_NO             VARCHAR2(10 BYTE),
  CHEQ_STAT            VARCHAR2(1 BYTE),
  DOCUMENT_NO          VARCHAR2(12 BYTE),
  BANK_CLEARANCE_DATE  DATE,
  IS_PRINT             VARCHAR2(1 BYTE),
  BANK_REF_NO          VARCHAR2(50 BYTE),
  CHECKED_BY           VARCHAR2(9 BYTE),
  IS_ACNT_PAYEE        VARCHAR2(1 BYTE)
)
TABLESPACE NPLEPF_DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX NPLGRA.EPF_EMP_FINAL_PAY_DTL_PK ON NPLGRA.EPF_EMP_FINAL_PAY_DTL
(EMP_CODE, COA_CODE)
LOGGING
TABLESPACE NPLEPF_DATA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE UNIQUE INDEX NPLGRA.PK_GL_CHEQ_DTL ON NPLGRA.GL_CHEQ_DTL
(SLNO, CHEQ_REF_NO, CHEQP_NO)
LOGGING
TABLESPACE NPLEPF_DATA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


ALTER TABLE NPLGRA.EPF_CONTRI_MST ADD (
  CONSTRAINT EPF_CONTRI_MST_PK
 PRIMARY KEY
 (EMP_CODE, MNYR_CON)
    USING INDEX 
    TABLESPACE NPLEPF_DATA
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                NEXT             1M
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                PCTINCREASE      0
               ));

ALTER TABLE NPLGRA.EPF_EMP_FINAL_PAY_MST ADD (
  CONSTRAINT EPF_EMP_FINAL_PAY_MST_PK
 PRIMARY KEY
 (EMP_CODE)
    USING INDEX 
    TABLESPACE NPLEPF_DATA
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                NEXT             1M
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                PCTINCREASE      0
               ));

ALTER TABLE NPLGRA.EPF_EMP_PROFIT_DIST ADD (
  CONSTRAINT EPF_EMP_PROFIT_DIST_PK
 PRIMARY KEY
 (PF_ID, MNYR)
    USING INDEX 
    TABLESPACE NPLEPF_DATA
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                NEXT             1M
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                PCTINCREASE      0
               ));

ALTER TABLE NPLGRA.EPF_LOAN_ADJUST_UPD ADD (
  CONSTRAINT EMP_CODE_PK
 PRIMARY KEY
 (EMP_CODE, MNYR)
    USING INDEX 
    TABLESPACE NPLEPF_DATA
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                NEXT             1M
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                PCTINCREASE      0
               ));

ALTER TABLE NPLGRA.EPF_MEMBER_ENROL_MST ADD (
  CONSTRAINT EPF_MEMBER_ENROL_MST_PK
 PRIMARY KEY
 (EMP_CODE)
    USING INDEX 
    TABLESPACE NPLEPF_DATA
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          128K
                NEXT             1M
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                PCTINCREASE      0
               ));

ALTER TABLE NPLGRA.EPF_MEM_REG_UPD ADD (
  CONSTRAINT EPF_MEM_REG_UPD_PK
 PRIMARY KEY
 (EMP_CODE, MNYR, VC_NO) DISABLE);

ALTER TABLE NPLGRA.EPF_NOMINEE ADD (
  CONSTRAINT EPF_NOMINEE_PK
 PRIMARY KEY
 (EMP_CODE, NOM_TYPE)
    USING INDEX 
    TABLESPACE NPLEPF_DATA
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                NEXT             1M
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                PCTINCREASE      0
               ));

ALTER TABLE NPLGRA.GL_BANK_ACNT ADD (
  CONSTRAINT PK_GL_BANK_ACNT
 PRIMARY KEY
 (ACNT_SLNO)
    USING INDEX 
    TABLESPACE NPLEPF_DATA
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                NEXT             1M
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                PCTINCREASE      0
               ));

ALTER TABLE NPLGRA.GL_BANK_ACNT_FACI_TYPE ADD (
  CONSTRAINT PK_GL_BANK_ACNT_FACI_TYPE
 PRIMARY KEY
 (ACNT_FCODE)
    USING INDEX 
    TABLESPACE NPLEPF_DATA
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                NEXT             1M
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                PCTINCREASE      0
               ));

ALTER TABLE NPLGRA.GL_BANK_ACNT_TYPE ADD (
  CONSTRAINT PK_GL_BANK_ACNT_TYPE
 PRIMARY KEY
 (ACNT_TCODE)
    USING INDEX 
    TABLESPACE NPLEPF_DATA
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                NEXT             1M
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                PCTINCREASE      0
               ));

ALTER TABLE NPLGRA.GL_BANK_COA_SETUP ADD (
  CONSTRAINT PK_GL_BANK_COA_SETUP
 PRIMARY KEY
 (ACNT_SLNO)
    USING INDEX 
    TABLESPACE NPLEPF_DATA
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                NEXT             1M
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                PCTINCREASE      0
               ));

ALTER TABLE NPLGRA.GL_CHEQ_MAIN ADD (
  CONSTRAINT PK_GL_CHEQ_MAIN
 PRIMARY KEY
 (SLNO, CHEQ_REF_NO)
    USING INDEX 
    TABLESPACE NPLEPF_DATA
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                NEXT             1M
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                PCTINCREASE      0
               ));

ALTER TABLE NPLGRA.GL_COA ADD (
  CONSTRAINT PK_GL_COA
 PRIMARY KEY
 (COA_CODE)
    USING INDEX 
    TABLESPACE NPLEPF_DATA
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                NEXT             1M
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                PCTINCREASE      0
               ));

ALTER TABLE NPLGRA.GL_COA_CODE_LEVEL ADD (
  CONSTRAINT PK_GL_COA_CODE_LEVEL
 PRIMARY KEY
 (LEVEL_COMP_ID, LEVEL_SLNO)
    USING INDEX 
    TABLESPACE NPLEPF_DATA
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                NEXT             1M
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                PCTINCREASE      0
               ));

ALTER TABLE NPLGRA.GL_COA_HISTORY ADD (
  CONSTRAINT PK_GL_COA_HISTORY
 PRIMARY KEY
 (SLNO)
    USING INDEX 
    TABLESPACE NPLEPF_DATA
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                NEXT             1M
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                PCTINCREASE      0
               ));

ALTER TABLE NPLGRA.GL_COMPANY ADD (
  CONSTRAINT PK_GL_COMPANY
 PRIMARY KEY
 (COMP_ID)
    USING INDEX 
    TABLESPACE NPLEPF_DATA
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                NEXT             1M
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                PCTINCREASE      0
               ));

ALTER TABLE NPLGRA.GL_CURRENCY ADD (
  CONSTRAINT PK_GL_CURRENCY
 PRIMARY KEY
 (CUR_CODE)
    USING INDEX 
    TABLESPACE NPLEPF_DATA
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                NEXT             1M
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                PCTINCREASE      0
               ));

ALTER TABLE NPLGRA.GL_PAYEE ADD (
  CONSTRAINT PK_GL_PAYEE
 PRIMARY KEY
 (PAYEE_CODE)
    USING INDEX 
    TABLESPACE NPLEPF_DATA
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          256K
                NEXT             1M
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                PCTINCREASE      0
               ));

ALTER TABLE NPLGRA.GL_PAYEE_TYPE ADD (
  CONSTRAINT PK_GL_PAYEE_TYPE
 PRIMARY KEY
 (SLNO)
    USING INDEX 
    TABLESPACE NPLEPF_DATA
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                NEXT             1M
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                PCTINCREASE      0
               ));

ALTER TABLE NPLGRA.GL_PAY_MODE ADD (
  CONSTRAINT PK_GL_PAY_MODE
 PRIMARY KEY
 (PM_CODE)
    USING INDEX 
    TABLESPACE NPLEPF_DATA
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                NEXT             1M
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                PCTINCREASE      0
               ));

ALTER TABLE NPLGRA.GL_PERIOD ADD (
  CONSTRAINT PK_GL_PERIOD
 PRIMARY KEY
 (CAL_CODE, CAL_DATE_FROM)
    USING INDEX 
    TABLESPACE NPLEPF_DATA
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                NEXT             1M
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                PCTINCREASE      0
               ));

ALTER TABLE NPLGRA.GL_RC ADD (
  CONSTRAINT PK_GL_RC
 PRIMARY KEY
 (RC_CODE)
    USING INDEX 
    TABLESPACE NPLEPF_DATA
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                NEXT             1M
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                PCTINCREASE      0
               ));

ALTER TABLE NPLGRA.GL_RC_LIST ADD (
  CONSTRAINT PK_GL_RC_LIST
 PRIMARY KEY
 (COA_CODE, RC_CODE)
    USING INDEX 
    TABLESPACE NPLEPF_DATA
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                NEXT             1M
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                PCTINCREASE      0
               ));

ALTER TABLE NPLGRA.GL_USER_VJ_PREF ADD (
  CONSTRAINT PK_GL_USER_VJ_PREF
 PRIMARY KEY
 (USER_ID, VJ_CODE)
    USING INDEX 
    TABLESPACE NPLEPF_DATA
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                NEXT             1M
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                PCTINCREASE      0
               ));

ALTER TABLE NPLGRA.GL_VJ_TYPE ADD (
  CONSTRAINT PK_GL_VJ_TYPE
 PRIMARY KEY
 (VJ_CODE)
    USING INDEX 
    TABLESPACE NPLEPF_DATA
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                NEXT             1M
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                PCTINCREASE      0
               ));

ALTER TABLE NPLGRA.GL_VOUCHER_DETAIL ADD (
  CONSTRAINT PK_GL_VOUCHER_DETAIL
 PRIMARY KEY
 (VC_NO, COA_CODE, RC_CODE, SLNO)
    USING INDEX 
    TABLESPACE NPLEPF_DATA
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          3M
                NEXT             1M
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                PCTINCREASE      0
               ));

ALTER TABLE NPLGRA.GL_VOUCHER_MAIN ADD (
  CONSTRAINT PK_GL_VOUCHER_MAIN
 PRIMARY KEY
 (VC_NO)
    USING INDEX 
    TABLESPACE NPLEPF_DATA
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                NEXT             1M
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                PCTINCREASE      0
               ));

ALTER TABLE NPLGRA.EPF_EMP_FINAL_PAY_DTL ADD (
  CONSTRAINT EPF_EMP_FINAL_PAY_DTL_PK
 PRIMARY KEY
 (EMP_CODE, COA_CODE)
    USING INDEX 
    TABLESPACE NPLEPF_DATA
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                NEXT             1M
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                PCTINCREASE      0
               ));

ALTER TABLE NPLGRA.GL_CHEQ_DTL ADD (
  CONSTRAINT PK_GL_CHEQ_DTL
 PRIMARY KEY
 (SLNO, CHEQ_REF_NO, CHEQP_NO)
    USING INDEX 
    TABLESPACE NPLEPF_DATA
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                NEXT             1M
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                PCTINCREASE      0
               ));

ALTER TABLE NPLGRA.EPF_NOMINEE ADD (
  CONSTRAINT FK_EPF_NOMINEE 
 FOREIGN KEY (EMP_CODE) 
 REFERENCES NPLGRA.EPF_MEMBER_ENROL_MST (EMP_CODE));

ALTER TABLE NPLGRA.GL_BANK_COA_SETUP ADD (
  CONSTRAINT FK_GL_BANK_COA_SETUP 
 FOREIGN KEY (ACNT_SLNO) 
 REFERENCES NPLGRA.GL_BANK_ACNT (ACNT_SLNO));

ALTER TABLE NPLGRA.EPF_EMP_FINAL_PAY_DTL ADD (
  CONSTRAINT FK_EPF_FINAL_PAY_COA 
 FOREIGN KEY (COA_CODE) 
 REFERENCES NPLGRA.GL_COA (COA_CODE),
  CONSTRAINT FK_EPF_EMP_FINAL_PAY_DTL 
 FOREIGN KEY (EMP_CODE) 
 REFERENCES NPLGRA.EPF_EMP_FINAL_PAY_MST (EMP_CODE));

ALTER TABLE NPLGRA.GL_CHEQ_DTL ADD (
  CONSTRAINT FK_GL_CHEQ_DTL 
 FOREIGN KEY (SLNO, CHEQ_REF_NO) 
 REFERENCES NPLGRA.GL_CHEQ_MAIN (SLNO,CHEQ_REF_NO));

GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON NPLGRA.EPF_MEMBER_ENROL_MST TO PMIS;

