DROP TABLE SMISEXP.CONSIGNEE CASCADE CONSTRAINTS;

CREATE TABLE SMISEXP.CONSIGNEE
(
  CUST_CODE     VARCHAR2(10 BYTE),
  CONSIG_CODE   VARCHAR2(7 BYTE),
  CONSIG_NAME   VARCHAR2(100 BYTE),
  CONSIG_VALID  VARCHAR2(1 BYTE),
  CONT_PERSON   VARCHAR2(50 BYTE),
  EMAIL         VARCHAR2(100 BYTE),
  PHONE_NO      VARCHAR2(50 BYTE),
  CELL_NO       VARCHAR2(50 BYTE),
  ADDRESS       VARCHAR2(100 BYTE),
  ENTRY_DT      DATE,
  USER_ID       VARCHAR2(10 BYTE)
)
TABLESPACE SMISEXP_DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


ALTER TABLE SMISEXP.CUSTOMER
 DROP PRIMARY KEY CASCADE;

DROP TABLE SMISEXP.CUSTOMER CASCADE CONSTRAINTS;

CREATE TABLE SMISEXP.CUSTOMER
(
  CUST_CODE     VARCHAR2(10 BYTE),
  CUST_NAME     VARCHAR2(100 BYTE),
  COUNTRY_CODE  VARCHAR2(2 BYTE),
  PAYMENT_CON   VARCHAR2(2 BYTE),
  ADV_PCT       NUMBER(3),
  CR_PCT        NUMBER(3),
  CR_CON        VARCHAR2(100 BYTE),
  CR_TERM       VARCHAR2(100 BYTE),
  CR_APPROVED   VARCHAR2(10 BYTE),
  CUSTSTAT      VARCHAR2(10 BYTE),
  ENTER_DT      DATE,
  USER_ID       NUMBER(10),
  MPO_CODE      VARCHAR2(5 BYTE),
  CTYPE_PCT     NUMBER(8,2)
)
TABLESPACE SMISEXP_DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


ALTER TABLE SMISEXP.CUSTOMER_DTL
 DROP PRIMARY KEY CASCADE;

DROP TABLE SMISEXP.CUSTOMER_DTL CASCADE CONSTRAINTS;

CREATE TABLE SMISEXP.CUSTOMER_DTL
(
  CUST_CODE     VARCHAR2(10 BYTE),
  CUST_ADDID    VARCHAR2(3 BYTE),
  CONT_PURPOSE  VARCHAR2(100 BYTE),
  CONT_PERSON   VARCHAR2(100 BYTE),
  EMAIL         VARCHAR2(100 BYTE),
  PHONE_NO      VARCHAR2(50 BYTE),
  CELL_NO       VARCHAR2(50 BYTE),
  ADDRESS       VARCHAR2(100 BYTE),
  USER_ID       VARCHAR2(10 BYTE),
  ENTER_DT      DATE
)
TABLESPACE SMISEXP_DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


ALTER TABLE SMISEXP.CUSTOMER_MV
 DROP PRIMARY KEY CASCADE;

DROP TABLE SMISEXP.CUSTOMER_MV CASCADE CONSTRAINTS;

CREATE TABLE SMISEXP.CUSTOMER_MV
(
  CUST_CODE     VARCHAR2(10 BYTE),
  CUST_NAME     VARCHAR2(100 BYTE),
  COUNTRY_CODE  VARCHAR2(2 BYTE),
  PAYMENT_CON   VARCHAR2(2 BYTE),
  ADV_PCT       NUMBER(3),
  CR_PCT        NUMBER(3),
  CR_CON        VARCHAR2(100 BYTE),
  CR_TERM       VARCHAR2(100 BYTE),
  CR_APPROVED   VARCHAR2(10 BYTE),
  CUSTSTAT      VARCHAR2(10 BYTE),
  ENTER_DT      DATE,
  USER_ID       NUMBER(10),
  MPO_CODE      VARCHAR2(5 BYTE),
  CTYPE_PCT     NUMBER(8,2)
)
TABLESPACE SMISEXP_DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


DROP TABLE SMISEXP.EXP_CASH CASCADE CONSTRAINTS;

CREATE TABLE SMISEXP.EXP_CASH
(
  VCNO         VARCHAR2(10 BYTE)                NOT NULL,
  VDATE        DATE,
  INVNO        VARCHAR2(10 BYTE),
  CH_DD        VARCHAR2(1 BYTE),
  PARTICUL     VARCHAR2(100 BYTE),
  DBAMNT       NUMBER(15,2),
  CRAMNT       NUMBER(15,2),
  TAXAMT       NUMBER(10,2),
  OTHAMT       NUMBER(10,2),
  CHEQ_STAT    VARCHAR2(1 BYTE),
  USER_ID      VARCHAR2(10 BYTE),
  ENTER_DT     DATE,
  BANK_CODE    VARCHAR2(4 BYTE),
  VC_STAT      VARCHAR2(1 BYTE),
  RECV_ORD_NO  VARCHAR2(10 BYTE),
  CUST_CODE    VARCHAR2(7 BYTE),
  BRANCH_CODE  VARCHAR2(3 BYTE)
)
TABLESPACE SMISEXP_DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


DROP TABLE SMISEXP.EXP_INVO_PAY_MODE CASCADE CONSTRAINTS;

CREATE TABLE SMISEXP.EXP_INVO_PAY_MODE
(
  PAY_CODE  VARCHAR2(2 BYTE),
  PAY_DESC  VARCHAR2(50 BYTE)
)
TABLESPACE SMISEXP_DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


DROP TABLE SMISEXP.EXP_ORDITEM_BT CASCADE CONSTRAINTS;

CREATE TABLE SMISEXP.EXP_ORDITEM_BT
(
  ORD_NO         VARCHAR2(10 BYTE),
  P_CODE         VARCHAR2(4 BYTE),
  PBOM_CODE      VARCHAR2(5 BYTE),
  PTYPE_CODE     VARCHAR2(1 BYTE),
  GEN_MAIN_CODE  VARCHAR2(6 BYTE),
  ORD_QNTY       NUMBER,
  PRICE          NUMBER,
  PROD_VAT       NUMBER,
  ACT_VALUE      NUMBER,
  VAT_VALUE      NUMBER,
  DIS_VALUE      NUMBER,
  NET_VALUE      NUMBER,
  ENTRY_DT       DATE,
  USER_ID        VARCHAR2(10 BYTE),
  CNCL_FLAG      VARCHAR2(1 BYTE),
  CNCL_REASON    VARCHAR2(20 BYTE),
  CNCL_BY        VARCHAR2(10 BYTE),
  CNCL_DT        DATE,
  PRICE_VAL      VARCHAR2(20 BYTE),
  REG_VAL        VARCHAR2(20 BYTE)
)
TABLESPACE SMISEXP_DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


DROP TABLE SMISEXP.EXP_ORDITEM_HIST CASCADE CONSTRAINTS;

CREATE TABLE SMISEXP.EXP_ORDITEM_HIST
(
  ORD_NO         VARCHAR2(10 BYTE),
  P_CODE         VARCHAR2(4 BYTE),
  PBOM_CODE      VARCHAR2(5 BYTE),
  PTYPE_CODE     VARCHAR2(1 BYTE),
  GEN_MAIN_CODE  VARCHAR2(6 BYTE),
  ORD_QNTY       NUMBER,
  PRICE          NUMBER,
  PROD_VAT       NUMBER,
  ACT_VALUE      NUMBER,
  VAT_VALUE      NUMBER,
  DIS_VALUE      NUMBER,
  NET_VALUE      NUMBER,
  ENTRY_DT       DATE,
  USER_ID        VARCHAR2(10 BYTE),
  CNCL_FLAG      VARCHAR2(1 BYTE),
  CNCL_REASON    VARCHAR2(20 BYTE),
  CNCL_BY        VARCHAR2(10 BYTE),
  CNCL_DT        DATE,
  PRICE_VAL      VARCHAR2(20 BYTE),
  REG_VAL        VARCHAR2(20 BYTE),
  HIST_DT        DATE,
  HIST_BY        VARCHAR2(5 BYTE)
)
TABLESPACE SMISEXP_DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          256K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


ALTER TABLE SMISEXP.EXP_ORDMAIN
 DROP PRIMARY KEY CASCADE;

DROP TABLE SMISEXP.EXP_ORDMAIN CASCADE CONSTRAINTS;

CREATE TABLE SMISEXP.EXP_ORDMAIN
(
  ORD_NO          VARCHAR2(10 BYTE),
  ORD_DT          DATE,
  ORD_NO_MNL      VARCHAR2(35 BYTE),
  ORD_MNL_DT      DATE,
  MANUFAC_CODE    VARCHAR2(10 BYTE),
  CUST_CODE       VARCHAR2(10 BYTE),
  CUST_ADDID      VARCHAR2(3 BYTE),
  CONSIG_CODE     VARCHAR2(10 BYTE),
  NOTIFY_CODE     VARCHAR2(10 BYTE),
  LC_NO           VARCHAR2(30 BYTE),
  LC_DT           DATE,
  TERMS_CODE      VARCHAR2(3 BYTE),
  PAY_TERMS       VARCHAR2(100 BYTE),
  PAY_CON         VARCHAR2(100 BYTE),
  PAY_RCV_AMNT    NUMBER,
  EST_SHIP_CHARG  NUMBER,
  EST_SHIP_PREM   NUMBER,
  DIS_PCT         NUMBER,
  ORD_CUR_MODE    VARCHAR2(4 BYTE),
  HS_CODE         VARCHAR2(20 BYTE),
  PORT_ADD        VARCHAR2(100 BYTE),
  SHIP_MODE       VARCHAR2(1 BYTE),
  PRICE_DT        DATE,
  PART_SHIP_FLAG  VARCHAR2(1 BYTE),
  INV_NO          VARCHAR2(10 BYTE),
  INV_DT          DATE,
  ENTRY_DT        DATE,
  USER_ID         VARCHAR2(5 BYTE),
  CNCL_FLAG       VARCHAR2(1 BYTE),
  CNCL_REASON     VARCHAR2(20 BYTE),
  CNCL_BY         VARCHAR2(10 BYTE),
  CNCL_DT         DATE,
  SHIP_PAY        VARCHAR2(1 BYTE),
  PROD_MON        DATE,
  SHIP_DT         DATE
)
TABLESPACE SMISEXP_DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


DROP TABLE SMISEXP.EXP_ORDMAIN_BK CASCADE CONSTRAINTS;

CREATE TABLE SMISEXP.EXP_ORDMAIN_BK
(
  ORD_NO          VARCHAR2(10 BYTE),
  ORD_DT          DATE,
  ORD_NO_MNL      VARCHAR2(15 BYTE),
  ORD_MNL_DT      DATE,
  MANUFAC_CODE    VARCHAR2(10 BYTE),
  CUST_CODE       VARCHAR2(10 BYTE),
  CONSIG_CODE     VARCHAR2(10 BYTE),
  NOTIFY_CODE     VARCHAR2(10 BYTE),
  LC_NO           VARCHAR2(30 BYTE),
  LC_DT           DATE,
  TERMS_CODE      VARCHAR2(3 BYTE),
  PAY_TERMS       VARCHAR2(30 BYTE),
  PAY_CON         VARCHAR2(30 BYTE),
  PAY_RCV_AMNT    NUMBER,
  EST_SHIP_CHARG  NUMBER,
  EST_SHIP_PREM   NUMBER,
  DIS_PCT         NUMBER,
  ORD_CUR_MODE    VARCHAR2(4 BYTE),
  HS_CODE         VARCHAR2(10 BYTE),
  PORT_ADD        VARCHAR2(100 BYTE),
  SHIP_MODE       VARCHAR2(1 BYTE),
  PRICE_DT        DATE,
  PART_SHIP_FLAG  VARCHAR2(1 BYTE),
  INV_NO          VARCHAR2(10 BYTE),
  INV_DT          DATE,
  ENTRY_DT        DATE,
  USER_ID         VARCHAR2(5 BYTE),
  CNCL_FLAG       VARCHAR2(1 BYTE),
  CNCL_REASON     VARCHAR2(20 BYTE),
  CNCL_BY         VARCHAR2(10 BYTE),
  CNCL_DT         DATE
)
TABLESPACE SMISEXP_DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


DROP TABLE SMISEXP.EXP_ORDMAIN_BT CASCADE CONSTRAINTS;

CREATE TABLE SMISEXP.EXP_ORDMAIN_BT
(
  ORD_NO          VARCHAR2(10 BYTE),
  ORD_DT          DATE,
  ORD_NO_MNL      VARCHAR2(35 BYTE),
  ORD_MNL_DT      DATE,
  MANUFAC_CODE    VARCHAR2(10 BYTE),
  CUST_CODE       VARCHAR2(10 BYTE),
  CUST_ADDID      VARCHAR2(3 BYTE),
  CONSIG_CODE     VARCHAR2(10 BYTE),
  NOTIFY_CODE     VARCHAR2(10 BYTE),
  LC_NO           VARCHAR2(30 BYTE),
  LC_DT           DATE,
  TERMS_CODE      VARCHAR2(3 BYTE),
  PAY_TERMS       VARCHAR2(100 BYTE),
  PAY_CON         VARCHAR2(100 BYTE),
  PAY_RCV_AMNT    NUMBER,
  EST_SHIP_CHARG  NUMBER,
  EST_SHIP_PREM   NUMBER,
  DIS_PCT         NUMBER,
  ORD_CUR_MODE    VARCHAR2(4 BYTE),
  HS_CODE         VARCHAR2(20 BYTE),
  PORT_ADD        VARCHAR2(100 BYTE),
  SHIP_MODE       VARCHAR2(1 BYTE),
  PRICE_DT        DATE,
  PART_SHIP_FLAG  VARCHAR2(1 BYTE),
  INV_NO          VARCHAR2(10 BYTE),
  INV_DT          DATE,
  ENTRY_DT        DATE,
  USER_ID         VARCHAR2(5 BYTE),
  CNCL_FLAG       VARCHAR2(1 BYTE),
  CNCL_REASON     VARCHAR2(20 BYTE),
  CNCL_BY         VARCHAR2(10 BYTE),
  CNCL_DT         DATE
)
TABLESPACE SMISEXP_DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


DROP TABLE SMISEXP.EXP_PRICE_TEMP CASCADE CONSTRAINTS;

CREATE TABLE SMISEXP.EXP_PRICE_TEMP
(
  PBOM_CODE   VARCHAR2(6 BYTE),
  PRICE       NUMBER,
  PRICE_DATE  DATE
)
TABLESPACE SMISEXP_DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


ALTER TABLE SMISEXP.INVOITEM
 DROP PRIMARY KEY CASCADE;

DROP TABLE SMISEXP.INVOITEM CASCADE CONSTRAINTS;

CREATE TABLE SMISEXP.INVOITEM
(
  INVNO       VARCHAR2(10 BYTE),
  P_CODE      VARCHAR2(5 BYTE),
  PROD_BATCH  VARCHAR2(6 BYTE),
  INVO_QNTY   NUMBER(8),
  PROD_RATE   NUMBER(7,2),
  PROD_VAT    NUMBER(7,2),
  BONU_QNTY   NUMBER(4),
  ACT_VALUE   NUMBER(12,2),
  DIS_VALUE   NUMBER(8,2),
  VAT_VALUE   NUMBER(8,2),
  NET_VALUE   NUMBER(12,2),
  TRNSTAT     VARCHAR2(1 BYTE),
  USER_ID     VARCHAR2(10 BYTE),
  ENTER_DT    DATE
)
TABLESPACE SMISEXP_DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


ALTER TABLE SMISEXP.INVOMAIN
 DROP PRIMARY KEY CASCADE;

DROP TABLE SMISEXP.INVOMAIN CASCADE CONSTRAINTS;

CREATE TABLE SMISEXP.INVOMAIN
(
  INVNO          VARCHAR2(10 BYTE),
  INVDATE        DATE,
  MPO_CODE       VARCHAR2(5 BYTE),
  MKT_CODE       VARCHAR2(6 BYTE),
  CUST_CODE      VARCHAR2(7 BYTE),
  EMPNO          VARCHAR2(6 BYTE),
  ACT_VALUE      NUMBER(12,2),
  DIS_VALUE      NUMBER(8,2),
  VAT_VALUE      NUMBER(8,2),
  NET_VALUE      NUMBER(12,2),
  CANC_DATE      DATE,
  TRNSTAT        VARCHAR2(1 BYTE),
  ORD_NO         VARCHAR2(10 BYTE),
  WHY_CANCEL     VARCHAR2(4 BYTE),
  CTYPE_PCT      NUMBER,
  PAID_STAT      VARCHAR2(1 BYTE),
  PAYMENT_MODE   VARCHAR2(10 BYTE),
  PAYMENT_AMNT   NUMBER,
  USER_ID        VARCHAR2(10 BYTE),
  ENTER_DT       DATE,
  EST_SHIP_CHAR  NUMBER,
  EST_INSU_PREM  NUMBER
)
TABLESPACE SMISEXP_DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


DROP TABLE SMISEXP.IN_CO_TERMS CASCADE CONSTRAINTS;

CREATE TABLE SMISEXP.IN_CO_TERMS
(
  TERMS_CODE  VARCHAR2(3 BYTE),
  TERMS_DESC  VARCHAR2(100 BYTE),
  TRANS_MODE  VARCHAR2(100 BYTE)
)
TABLESPACE SMISEXP_DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


DROP TABLE SMISEXP.NOTIFY CASCADE CONSTRAINTS;

CREATE TABLE SMISEXP.NOTIFY
(
  CUST_CODE     VARCHAR2(10 BYTE),
  NOTIFY_CODE   VARCHAR2(10 BYTE),
  NOTIFY_DESC   VARCHAR2(100 BYTE),
  NOTIFY_VALID  VARCHAR2(1 BYTE),
  CONT_PERSON   VARCHAR2(50 BYTE),
  ADDRESS       VARCHAR2(100 BYTE),
  EMAIL         VARCHAR2(100 BYTE),
  MOB_NO        VARCHAR2(50 BYTE),
  CELL_NO       VARCHAR2(50 BYTE),
  ENTRY_DT      DATE,
  USER_ID       VARCHAR2(10 BYTE)
)
TABLESPACE SMISEXP_DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


DROP TABLE SMISEXP.ORDITEM CASCADE CONSTRAINTS;

CREATE TABLE SMISEXP.ORDITEM
(
  ORD_NO     VARCHAR2(10 BYTE)                  NOT NULL,
  P_CODE     VARCHAR2(5 BYTE)                   NOT NULL,
  ORD_QNTY   NUMBER(6),
  PROD_RATE  NUMBER(7,2),
  PROD_VAT   NUMBER(7,2),
  INV_QNTY   NUMBER(6),
  ACT_VALUE  NUMBER(12,2),
  DIS_VALUE  NUMBER(8,2),
  VAT_VALUE  NUMBER(8,2),
  NET_VALUE  NUMBER(12,2),
  TRNSTAT    VARCHAR2(1 BYTE),
  USER_ID    VARCHAR2(10 BYTE),
  ENTER_DT   DATE
)
TABLESPACE SMISEXP_DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


DROP TABLE SMISEXP.ORDMAIN CASCADE CONSTRAINTS;

CREATE TABLE SMISEXP.ORDMAIN
(
  ORD_NO        VARCHAR2(10 BYTE)               NOT NULL,
  ORD_DATE      DATE,
  CUST_CODE     VARCHAR2(7 BYTE),
  MPO_CODE      VARCHAR2(5 BYTE),
  MKT_CODE      VARCHAR2(6 BYTE),
  ACT_VALUE     NUMBER(12,2),
  DIS_VALUE     NUMBER(8,2),
  VAT_VALUE     NUMBER(8,2),
  NET_VALUE     NUMBER(12,2),
  INVOICED      VARCHAR2(1 BYTE),
  ORD_CDATE     DATE,
  TRNSTAT       VARCHAR2(1 BYTE),
  NO_ITEM       NUMBER(3),
  INVNO         VARCHAR2(10 BYTE),
  INVDATE       DATE,
  INV_TRNSTAT   VARCHAR2(1 BYTE),
  PAYMENT_MODE  VARCHAR2(10 BYTE),
  CTYPE_PCT     NUMBER(8,2),
  USER_ID       VARCHAR2(10 BYTE),
  ENTER_DT      DATE,
  CONV_RATE     NUMBER(8,2)
)
TABLESPACE SMISEXP_DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


ALTER TABLE SMISEXP.PRODUCT_EXP
 DROP PRIMARY KEY CASCADE;

DROP TABLE SMISEXP.PRODUCT_EXP CASCADE CONSTRAINTS;

CREATE TABLE SMISEXP.PRODUCT_EXP
(
  COUNTRY_CODE      VARCHAR2(6 BYTE),
  CUST_CODE         VARCHAR2(10 BYTE),
  COM_CODE          VARCHAR2(3 BYTE),
  TPC_CODE          VARCHAR2(3 BYTE),
  PCAT_CODE         VARCHAR2(5 BYTE),
  P_CODE            VARCHAR2(4 BYTE),
  P_N_CODE          VARCHAR2(12 BYTE),
  P_N_DESC          VARCHAR2(100 BYTE),
  GEN_MAIN_CODE     VARCHAR2(6 BYTE),
  PACK_SIZE         VARCHAR2(10 BYTE),
  PACK_SIZE1        NUMBER(2),
  PACK_SIZE2        NUMBER(3),
  SELF_LIFE         NUMBER(4,2),
  BATCH_SIZE        NUMBER(12),
  INN_PACK          NUMBER(6),
  SP_PACK           NUMBER(6),
  IC_LN             NUMBER(6,2),
  IC_WD             NUMBER(6,2),
  IC_HT             NUMBER(6,2),
  SP_LN             NUMBER(6,2),
  SP_WD             NUMBER(6,2),
  SP_HT             NUMBER(6,2),
  GW_WEIGHT         NUMBER(6),
  VISA_NO           VARCHAR2(15 BYTE),
  VISA_ISSU_DT      DATE,
  VISA_EXP_DT       DATE,
  TERMS_CODE        VARCHAR2(3 BYTE),
  SHIP_MODE         VARCHAR2(1 BYTE),
  UTP               NUMBER(12,4),
  UVP               NUMBER(12,4),
  UMRP              NUMBER(12,4),
  COMM_TP           NUMBER(12,2),
  COMM_VP           NUMBER(12,2),
  COMM_MRP          NUMBER(12,2),
  CUR_MODE          VARCHAR2(4 BYTE),
  PRICE             NUMBER(12,4),
  PRICE_DATE        DATE,
  PRIMARY_PACK      VARCHAR2(30 BYTE),
  USER_ID           NUMBER(10),
  ENTER_DT          DATE,
  PP_LN             NUMBER(8,2),
  PP_WD             NUMBER(8,2),
  PP_HT             NUMBER(8,2),
  MC_LN             NUMBER(8,2),
  MC_WD             NUMBER(8,2),
  MC_HT             NUMBER(8,2),
  PLACE_DISCH       VARCHAR2(100 BYTE),
  PBOM_CODE         VARCHAR2(5 BYTE)            NOT NULL,
  VP_UNIT_RATE      NUMBER(14,4),
  PROMO_MON         DATE,
  RM_COST           NUMBER,
  PM_COST           NUMBER,
  FOH_VC_COST       NUMBER,
  FOH_FC_COST       NUMBER,
  URM_COST          NUMBER,
  UPM_COST          NUMBER,
  UVC_COST          NUMBER,
  UFC_COST          NUMBER,
  MKT_TYPE          VARCHAR2(2 BYTE),
  PRICE_VALID_DATE  DATE,
  PAY_TERM_CONDI    VARCHAR2(100 BYTE),
  REMB_PRICE        NUMBER
)
TABLESPACE SMISEXP_DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          128K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


DROP TABLE SMISEXP.PRODUCT_EXP_131020 CASCADE CONSTRAINTS;

CREATE TABLE SMISEXP.PRODUCT_EXP_131020
(
  COUNTRY_CODE   VARCHAR2(6 BYTE),
  CUST_CODE      VARCHAR2(10 BYTE),
  COM_CODE       VARCHAR2(3 BYTE),
  TPC_CODE       VARCHAR2(3 BYTE),
  PCAT_CODE      VARCHAR2(5 BYTE),
  P_CODE         VARCHAR2(4 BYTE),
  P_N_CODE       VARCHAR2(12 BYTE),
  P_N_DESC       VARCHAR2(100 BYTE),
  GEN_MAIN_CODE  VARCHAR2(6 BYTE),
  PACK_SIZE      VARCHAR2(10 BYTE),
  PACK_SIZE1     NUMBER(2),
  PACK_SIZE2     NUMBER(3),
  SELF_LIFE      NUMBER(4,2),
  BATCH_SIZE     NUMBER(12),
  INN_PACK       NUMBER(6),
  SP_PACK        NUMBER(6),
  IC_LN          NUMBER(6,2),
  IC_WD          NUMBER(6,2),
  IC_HT          NUMBER(6,2),
  SP_LN          NUMBER(6,2),
  SP_WD          NUMBER(6,2),
  SP_HT          NUMBER(6,2),
  GW_WEIGHT      NUMBER(6),
  VISA_NO        VARCHAR2(15 BYTE),
  VISA_ISSU_DT   DATE,
  VISA_EXP_DT    DATE,
  TERMS_CODE     VARCHAR2(3 BYTE),
  SHIP_MODE      VARCHAR2(1 BYTE),
  UTP            NUMBER(12,4),
  UVP            NUMBER(12,4),
  UMRP           NUMBER(12,4),
  COMM_TP        NUMBER(12,2),
  COMM_VP        NUMBER(12,2),
  COMM_MRP       NUMBER(12,2),
  CUR_MODE       VARCHAR2(3 BYTE),
  PRICE          NUMBER(12,4),
  PRICE_DATE     DATE,
  PRIMARY_PACK   VARCHAR2(30 BYTE),
  USER_ID        NUMBER(10),
  ENTER_DT       DATE,
  PP_LN          NUMBER(8,2),
  PP_WD          NUMBER(8,2),
  PP_HT          NUMBER(8,2),
  MC_LN          NUMBER(8,2),
  MC_WD          NUMBER(8,2),
  MC_HT          NUMBER(8,2),
  PLACE_DISCH    VARCHAR2(100 BYTE),
  PBOM_CODE      VARCHAR2(5 BYTE)               NOT NULL,
  VP_UNIT_RATE   NUMBER(14,4),
  PROMO_MON      DATE,
  RM_COST        NUMBER,
  PM_COST        NUMBER,
  FOH_VC_COST    NUMBER,
  FOH_FC_COST    NUMBER,
  URM_COST       NUMBER,
  UPM_COST       NUMBER,
  UVC_COST       NUMBER,
  UFC_COST       NUMBER
)
TABLESPACE SMISEXP_DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          128K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


DROP TABLE SMISEXP.PRODUCT_EXP_230220 CASCADE CONSTRAINTS;

CREATE TABLE SMISEXP.PRODUCT_EXP_230220
(
  COUNTRY_CODE   VARCHAR2(6 BYTE),
  CUST_CODE      VARCHAR2(10 BYTE),
  COM_CODE       VARCHAR2(3 BYTE),
  TPC_CODE       VARCHAR2(3 BYTE),
  PCAT_CODE      VARCHAR2(5 BYTE),
  P_CODE         VARCHAR2(4 BYTE),
  P_N_CODE       VARCHAR2(12 BYTE),
  P_N_DESC       VARCHAR2(100 BYTE),
  GEN_MAIN_CODE  VARCHAR2(6 BYTE),
  PACK_SIZE      VARCHAR2(10 BYTE),
  PACK_SIZE1     NUMBER(2),
  PACK_SIZE2     NUMBER(3),
  SELF_LIFE      NUMBER(4,2),
  BATCH_SIZE     NUMBER(12),
  INN_PACK       NUMBER(6),
  SP_PACK        NUMBER(6),
  IC_LN          NUMBER(6,2),
  IC_WD          NUMBER(6,2),
  IC_HT          NUMBER(6,2),
  SP_LN          NUMBER(6,2),
  SP_WD          NUMBER(6,2),
  SP_HT          NUMBER(6,2),
  GW_WEIGHT      NUMBER(6),
  VISA_NO        VARCHAR2(15 BYTE),
  VISA_ISSU_DT   DATE,
  VISA_EXP_DT    DATE,
  TERMS_CODE     VARCHAR2(3 BYTE),
  SHIP_MODE      VARCHAR2(1 BYTE),
  UTP            NUMBER(12,4),
  UVP            NUMBER(12,4),
  UMRP           NUMBER(12,4),
  COMM_TP        NUMBER(12,2),
  COMM_VP        NUMBER(12,2),
  COMM_MRP       NUMBER(12,2),
  CUR_MODE       VARCHAR2(3 BYTE),
  PRICE          NUMBER(12,4),
  PRICE_DATE     DATE,
  PRIMARY_PACK   VARCHAR2(30 BYTE),
  USER_ID        NUMBER(10),
  ENTER_DT       DATE,
  PP_LN          NUMBER(8,2),
  PP_WD          NUMBER(8,2),
  PP_HT          NUMBER(8,2),
  MC_LN          NUMBER(8,2),
  MC_WD          NUMBER(8,2),
  MC_HT          NUMBER(8,2),
  PLACE_DISCH    VARCHAR2(100 BYTE),
  PBOM_CODE      VARCHAR2(5 BYTE)               NOT NULL,
  VP_UNIT_RATE   NUMBER(14,4),
  PROMO_MON      DATE,
  RM_COST        NUMBER,
  PM_COST        NUMBER,
  FOH_VC_COST    NUMBER,
  FOH_FC_COST    NUMBER,
  URM_COST       NUMBER,
  UPM_COST       NUMBER,
  UVC_COST       NUMBER,
  UFC_COST       NUMBER
)
TABLESPACE SMISEXP_DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          128K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


DROP TABLE SMISEXP.PROD_EXP_UPD_101115 CASCADE CONSTRAINTS;

CREATE TABLE SMISEXP.PROD_EXP_UPD_101115
(
  COUNTRY_CODE   VARCHAR2(255 BYTE),
  COUNTRY_NAME   VARCHAR2(255 BYTE),
  CUST_CODE      VARCHAR2(255 BYTE),
  CUST_NAME      VARCHAR2(255 BYTE),
  P_CODE         VARCHAR2(255 BYTE),
  P_N_CODE       VARCHAR2(255 BYTE),
  P_N_DESC       VARCHAR2(255 BYTE),
  TPC_CODE       VARCHAR2(255 BYTE),
  TPC_DESC       VARCHAR2(255 BYTE),
  GEN_MAIN_CODE  VARCHAR2(255 BYTE),
  GEN_MAIN_DESC  VARCHAR2(255 BYTE),
  PACK_SIZE      VARCHAR2(255 BYTE),
  PROD_PACK      VARCHAR2(255 BYTE),
  VISA_NO        VARCHAR2(255 BYTE),
  VISA_ISSU_DT   DATE,
  VISA_EXP_DT    DATE,
  TERMS_CODE     VARCHAR2(255 BYTE),
  TERMS_DESC     VARCHAR2(255 BYTE),
  SHIP_MODE      VARCHAR2(255 BYTE),
  CUR_MODE       VARCHAR2(320 BYTE),
  PRICE          VARCHAR2(320 BYTE),
  PLACE_DISCH    VARCHAR2(255 BYTE)
)
TABLESPACE SMISEXP_DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


DROP TABLE SMISEXP.PROD_STOK CASCADE CONSTRAINTS;

CREATE TABLE SMISEXP.PROD_STOK
(
  PCAT_CODE     VARCHAR2(5 BYTE),
  P_CODE        VARCHAR2(5 BYTE)                NOT NULL,
  PROD_BATCH    VARCHAR2(6 BYTE)                NOT NULL,
  MFG_DATE      DATE,
  EXP_DATE      DATE,
  IN_QNTY       NUMBER(10),
  OUT_QNTY      NUMBER(10),
  STK_QNTY      NUMBER(10),
  USER_ID       VARCHAR2(10 BYTE),
  ENTER_DT      DATE,
  PROD_TYPE     VARCHAR2(1 BYTE),
  PINST_CODE    VARCHAR2(5 BYTE),
  INS_BACK      VARCHAR2(1 BYTE),
  STR_FLAG      VARCHAR2(1 BYTE),
  LS_OUT_QNTY   NUMBER(10),
  LS_STK_QNTY   NUMBER(10),
  BRK_QNTY      NUMBER(8),
  DMG_QNTY      NUMBER(8),
  TRANSIT_QNTY  NUMBER(8),
  DEXP_QNTY     NUMBER(10),
  CDMG_QNTY     NUMBER(10),
  NC_QNTY       NUMBER(10),
  FGS_TRNS      NUMBER(8),
  PC_TRNS       NUMBER(8)
)
TABLESPACE SMISEXP_DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


DROP TABLE SMISEXP.PROD_TEMP CASCADE CONSTRAINTS;

CREATE TABLE SMISEXP.PROD_TEMP
(
  P_CODE  VARCHAR2(5 BYTE),
  PRICE   NUMBER
)
TABLESPACE SMISEXP_DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


DROP TABLE SMISEXP.REC_ITEM CASCADE CONSTRAINTS;

CREATE TABLE SMISEXP.REC_ITEM
(
  REC_SLNO             VARCHAR2(8 BYTE)         NOT NULL,
  P_CODE               VARCHAR2(5 BYTE)         NOT NULL,
  PROD_BATCH           VARCHAR2(7 BYTE)         NOT NULL,
  PCAT_CODE            VARCHAR2(5 BYTE),
  MFG_DATE             DATE,
  EXP_DATE             DATE,
  REC_QNTY             NUMBER(8),
  PROD_RATE            NUMBER(8,2),
  USER_ID              VARCHAR2(10 BYTE),
  ENTER_DT             DATE,
  PROD_VAL             NUMBER(15,2),
  PROD_TYPE            VARCHAR2(1 BYTE),
  STR_FLAG             VARCHAR2(1 BYTE),
  ACTVAL               NUMBER(15,2),
  VATVAL               NUMBER(15,2),
  NETVAL               NUMBER(15,2),
  VAT_RATE             NUMBER(8,2),
  BRK_QNTY             NUMBER(6),
  DMG_QNTY             NUMBER(6),
  CDMG_QNTY            NUMBER(6),
  SHRT_QNTY            NUMBER(6),
  EXCE_QNTY            NUMBER(6),
  CHAL_QNTY            NUMBER(12),
  WRONG_BATCH          VARCHAR2(6 BYTE),
  PHY_QNTY             NUMBER(12),
  DIFFER_QNTY          NUMBER(12),
  PND_STAT             VARCHAR2(1 BYTE),
  CSIN_STAT            VARCHAR2(1 BYTE),
  MUSHAK_NO            VARCHAR2(30 BYTE),
  BATCH_STARTING_DATE  DATE,
  BATCH_ENDING_DATE    DATE
)
TABLESPACE SMISEXP_DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


DROP TABLE SMISEXP.REC_MAIN CASCADE CONSTRAINTS;

CREATE TABLE SMISEXP.REC_MAIN
(
  REC_SLNO      VARCHAR2(8 BYTE),
  REC_DATE      DATE,
  REC_TYPE      VARCHAR2(1 BYTE),
  REC_TO        VARCHAR2(5 BYTE),
  REC_FROM      VARCHAR2(5 BYTE),
  REC_CHLNO     VARCHAR2(10 BYTE),
  USER_ID       VARCHAR2(10 BYTE),
  ENTER_DT      DATE,
  REC_DEPOT     VARCHAR2(2 BYTE),
  FGS_TRANS_UP  VARCHAR2(1 BYTE),
  CONV_RATE     NUMBER(8,2)
)
TABLESPACE SMISEXP_DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


ALTER TABLE SMISEXP.SAM_PRODUCT_EXP
 DROP PRIMARY KEY CASCADE;

DROP TABLE SMISEXP.SAM_PRODUCT_EXP CASCADE CONSTRAINTS;

CREATE TABLE SMISEXP.SAM_PRODUCT_EXP
(
  COUNTRY_CODE   VARCHAR2(6 BYTE),
  CUST_CODE      VARCHAR2(10 BYTE),
  COM_CODE       VARCHAR2(3 BYTE),
  TPC_CODE       VARCHAR2(3 BYTE),
  PCAT_CODE      VARCHAR2(5 BYTE),
  P_CODE         VARCHAR2(4 BYTE),
  P_N_CODE       VARCHAR2(12 BYTE),
  P_DESC         VARCHAR2(100 BYTE),
  SBOM_CODE      VARCHAR2(5 BYTE),
  GEN_MAIN_CODE  VARCHAR2(6 BYTE),
  PACK_SIZE      VARCHAR2(10 BYTE),
  PACK_SIZE1     NUMBER(2),
  PACK_SIZE2     NUMBER(3),
  SELF_LIFE      NUMBER(4,2),
  BATCH_SIZE     NUMBER(12),
  INN_PACK       NUMBER(6),
  SP_PACK        NUMBER(6),
  IC_LN          NUMBER(6,2),
  IC_WD          NUMBER(6,2),
  IC_HT          NUMBER(6,2),
  SP_LN          NUMBER(6,2),
  SP_WD          NUMBER(6,2),
  SP_HT          NUMBER(6,2),
  GW_WEIGHT      NUMBER(6),
  VISA_NO        VARCHAR2(15 BYTE),
  VISA_ISSU_DT   DATE,
  VISA_EXP_DT    DATE,
  TERMS_CODE     VARCHAR2(3 BYTE),
  SHIP_MODE      VARCHAR2(1 BYTE),
  UTP            NUMBER(12,4),
  UVP            NUMBER(12,4),
  UMRP           NUMBER(12,4),
  COMM_TP        NUMBER(12,2),
  COMM_VP        NUMBER(12,2),
  COMM_MRP       NUMBER(12,2),
  CUR_MODE       VARCHAR2(4 BYTE),
  PRICE          NUMBER(12,2),
  PRICE_DATE     DATE,
  PRIMARY_PACK   VARCHAR2(30 BYTE),
  USER_ID        NUMBER(10),
  ENTER_DT       DATE,
  PP_LN          NUMBER(8,2),
  PP_WD          NUMBER(8,2),
  PP_HT          NUMBER(8,2),
  MC_LN          NUMBER(8,2),
  MC_WD          NUMBER(8,2),
  MC_HT          NUMBER(8,2),
  PLACE_DISCH    VARCHAR2(100 BYTE),
  VP_UNIT_RATE   NUMBER(14,4),
  PROMO_MON      DATE,
  RM_COST        NUMBER,
  PM_COST        NUMBER,
  FOH_VC_COST    NUMBER,
  FOH_FC_COST    NUMBER,
  URM_COST       NUMBER,
  UPM_COST       NUMBER,
  UVC_COST       NUMBER,
  UFC_COST       NUMBER
)
TABLESPACE SMISEXP_DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


DROP TABLE SMISEXP.TEMP CASCADE CONSTRAINTS;

CREATE TABLE SMISEXP.TEMP
(
  P_CODE    VARCHAR2(5 BYTE),
  UPD_RATE  NUMBER
)
TABLESPACE SMISEXP_DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


ALTER TABLE SMISEXP.TENDER_MAIN
 DROP PRIMARY KEY CASCADE;

DROP TABLE SMISEXP.TENDER_MAIN CASCADE CONSTRAINTS;

CREATE TABLE SMISEXP.TENDER_MAIN
(
  TEND_CODE   VARCHAR2(10 BYTE),
  TEND_DESC   VARCHAR2(100 BYTE),
  CUST_CODE   VARCHAR2(10 BYTE),
  CUST_ADDID  VARCHAR2(3 BYTE),
  REC_DATE    DATE,
  TEND_DATE   DATE,
  TO_DATE     DATE,
  OPEN_DATE   DATE,
  SUB_DATE    DATE,
  SCH_AMNT    NUMBER,
  OTH_EXPE    VARCHAR2(1 BYTE),
  OTH_AMNT    NUMBER,
  IS_QUOATED  VARCHAR2(1 BYTE),
  USER_ID     VARCHAR2(10 BYTE),
  ENTER_DT    DATE
)
TABLESPACE SMISEXP_DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


DROP TABLE SMISEXP.HPRODUCT_EXP CASCADE CONSTRAINTS;

CREATE TABLE SMISEXP.HPRODUCT_EXP
(
  COUNTRY_CODE   VARCHAR2(6 BYTE),
  CUST_CODE      VARCHAR2(10 BYTE),
  COM_CODE       VARCHAR2(3 BYTE),
  TPC_CODE       VARCHAR2(3 BYTE),
  PCAT_CODE      VARCHAR2(5 BYTE),
  P_CODE         VARCHAR2(4 BYTE),
  P_N_CODE       VARCHAR2(12 BYTE),
  P_N_DESC       VARCHAR2(100 BYTE),
  GEN_MAIN_CODE  VARCHAR2(6 BYTE),
  PACK_SIZE      VARCHAR2(10 BYTE),
  PACK_SIZE1     NUMBER(2),
  PACK_SIZE2     NUMBER(3),
  SELF_LIFE      NUMBER(4,2),
  BATCH_SIZE     NUMBER(12),
  INN_PACK       NUMBER(6),
  SP_PACK        NUMBER(6),
  IC_LN          NUMBER(6,2),
  IC_WD          NUMBER(6,2),
  IC_HT          NUMBER(6,2),
  SP_LN          NUMBER(6,2),
  SP_WD          NUMBER(6,2),
  SP_HT          NUMBER(6,2),
  GW_WEIGHT      NUMBER(6),
  VISA_NO        VARCHAR2(15 BYTE),
  VISA_ISSU_DT   DATE,
  VISA_EXP_DT    DATE,
  TERMS_CODE     VARCHAR2(3 BYTE),
  SHIP_MODE      VARCHAR2(1 BYTE),
  UTP            NUMBER(12,4),
  UVP            NUMBER(12,4),
  UMRP           NUMBER(12,4),
  COMM_TP        NUMBER(12,2),
  COMM_VP        NUMBER(12,2),
  COMM_MRP       NUMBER(12,2),
  CUR_MODE       VARCHAR2(3 BYTE),
  PRICE          NUMBER(12,4),
  PRICE_DATE     DATE,
  PRIMARY_PACK   VARCHAR2(30 BYTE),
  USER_ID        NUMBER(10),
  ENTER_DT       DATE,
  PP_LN          NUMBER(8,2),
  PP_WD          NUMBER(8,2),
  PP_HT          NUMBER(8,2),
  MC_LN          NUMBER(8,2),
  MC_WD          NUMBER(8,2),
  MC_HT          NUMBER(8,2),
  PLACE_DISCH    VARCHAR2(100 BYTE),
  PBOM_CODE      VARCHAR2(5 BYTE)               NOT NULL,
  VP_UNIT_RATE   NUMBER(14,4),
  PROMO_MON      DATE,
  RM_COST        NUMBER,
  PM_COST        NUMBER,
  FOH_VC_COST    NUMBER,
  FOH_FC_COST    NUMBER,
  URM_COST       NUMBER,
  UPM_COST       NUMBER,
  UVC_COST       NUMBER,
  UFC_COST       NUMBER,
  MKT_TYPE       VARCHAR2(2 BYTE),
  HENTER_DT      DATE,
  SLNO           VARCHAR2(10 BYTE)
)
TABLESPACE SMISEXP_DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


DROP TABLE SMISEXP.EXP_INVOMAIN_TEMP CASCADE CONSTRAINTS;

CREATE TABLE SMISEXP.EXP_INVOMAIN_TEMP
(
  INVNO             VARCHAR2(10 BYTE),
  INVDATE           DATE,
  INVNO_MNL         VARCHAR2(35 BYTE),
  ORD_NO            VARCHAR2(10 BYTE),
  CUST_CODE         VARCHAR2(10 BYTE),
  EXP_NO            VARCHAR2(35 BYTE),
  EXP_DATE          DATE,
  PORT_OF_LOAD      VARCHAR2(35 BYTE),
  SELLER_BANK_CODE  VARCHAR2(3 BYTE),
  BUYER_BANK_CODE   VARCHAR2(3 BYTE),
  ACT_VALUE         NUMBER,
  VAT_VALUE         NUMBER,
  NET_VALUE         NUMBER,
  CANC_DATE         DATE,
  TRNSTAT           VARCHAR2(1 BYTE),
  PAID_STAT         VARCHAR2(1 BYTE),
  PAYMENT_MODE      VARCHAR2(10 BYTE),
  PAYMENT_AMNT      NUMBER,
  USER_ID           VARCHAR2(10 BYTE),
  ENTER_DATE        DATE,
  SHIPING_CHARGE    NUMBER,
  INSURANCE_CHARGE  NUMBER,
  PROMO_MAT_FLAG    VARCHAR2(1 BYTE)
)
TABLESPACE SMISEXP_DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


ALTER TABLE SMISEXP.EXP_INVOMAIN
 DROP PRIMARY KEY CASCADE;

DROP TABLE SMISEXP.EXP_INVOMAIN CASCADE CONSTRAINTS;

CREATE TABLE SMISEXP.EXP_INVOMAIN
(
  INVNO             VARCHAR2(10 BYTE),
  INVDATE           DATE,
  INVNO_MNL         VARCHAR2(35 BYTE),
  INVNO_MNL_DT      DATE,
  ORD_NO            VARCHAR2(10 BYTE),
  CUST_CODE         VARCHAR2(10 BYTE),
  EXP_NO            VARCHAR2(35 BYTE),
  EXP_DATE          DATE,
  PORT_OF_LOAD      VARCHAR2(35 BYTE),
  SELLER_BANK_CODE  VARCHAR2(3 BYTE),
  BUYER_BANK_CODE   VARCHAR2(3 BYTE),
  LC_NO             VARCHAR2(30 BYTE),
  LC_DT             DATE,
  ACT_VALUE         NUMBER,
  VAT_VALUE         NUMBER,
  NET_VALUE         NUMBER,
  CANC_DATE         DATE,
  TRNSTAT           VARCHAR2(1 BYTE),
  PAID_STAT         VARCHAR2(1 BYTE),
  PAYMENT_MODE      VARCHAR2(10 BYTE),
  PAYMENT_AMNT      NUMBER,
  USER_ID           VARCHAR2(10 BYTE),
  ENTER_DATE        DATE,
  SHIPING_CHARGE    NUMBER,
  INSURANCE_CHARGE  NUMBER,
  PROMO_MAT_FLAG    VARCHAR2(1 BYTE)
)
TABLESPACE SMISEXP_DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


DROP TABLE SMISEXP.PROD_EXP_UPD_TMP CASCADE CONSTRAINTS;

CREATE TABLE SMISEXP.PROD_EXP_UPD_TMP
(
  PBOM_CODE      VARCHAR2(5 BYTE),
  P_N_DESC_EXT   VARCHAR2(100 BYTE),
  P_N_DESC       VARCHAR2(100 BYTE),
  GEN_MAIN_DESC  VARCHAR2(500 BYTE)
)
TABLESPACE SMISEXP_DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


ALTER TABLE SMISEXP.EXP_PROD_GEN
 DROP PRIMARY KEY CASCADE;

DROP TABLE SMISEXP.EXP_PROD_GEN CASCADE CONSTRAINTS;

CREATE TABLE SMISEXP.EXP_PROD_GEN
(
  P_CODE         VARCHAR2(5 BYTE),
  GEN_MAIN_CODE  VARCHAR2(6 BYTE),
  GEN_MAIN_DESC  VARCHAR2(500 BYTE)
)
TABLESPACE SMISEXP_DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


DROP TABLE SMISEXP.PRODUCT_EXP_BKUP CASCADE CONSTRAINTS;

CREATE TABLE SMISEXP.PRODUCT_EXP_BKUP
(
  COUNTRY_CODE      VARCHAR2(6 BYTE),
  CUST_CODE         VARCHAR2(10 BYTE),
  COM_CODE          VARCHAR2(3 BYTE),
  TPC_CODE          VARCHAR2(3 BYTE),
  PCAT_CODE         VARCHAR2(5 BYTE),
  P_CODE            VARCHAR2(4 BYTE),
  P_N_CODE          VARCHAR2(12 BYTE),
  P_N_DESC          VARCHAR2(100 BYTE),
  GEN_MAIN_CODE     VARCHAR2(6 BYTE),
  PACK_SIZE         VARCHAR2(10 BYTE),
  PACK_SIZE1        NUMBER(2),
  PACK_SIZE2        NUMBER(3),
  SELF_LIFE         NUMBER(4,2),
  BATCH_SIZE        NUMBER(12),
  INN_PACK          NUMBER(6),
  SP_PACK           NUMBER(6),
  IC_LN             NUMBER(6,2),
  IC_WD             NUMBER(6,2),
  IC_HT             NUMBER(6,2),
  SP_LN             NUMBER(6,2),
  SP_WD             NUMBER(6,2),
  SP_HT             NUMBER(6,2),
  GW_WEIGHT         NUMBER(6),
  VISA_NO           VARCHAR2(15 BYTE),
  VISA_ISSU_DT      DATE,
  VISA_EXP_DT       DATE,
  TERMS_CODE        VARCHAR2(3 BYTE),
  SHIP_MODE         VARCHAR2(1 BYTE),
  UTP               NUMBER(12,4),
  UVP               NUMBER(12,4),
  UMRP              NUMBER(12,4),
  COMM_TP           NUMBER(12,2),
  COMM_VP           NUMBER(12,2),
  COMM_MRP          NUMBER(12,2),
  CUR_MODE          VARCHAR2(4 BYTE),
  PRICE             NUMBER(12,4),
  PRICE_DATE        DATE,
  PRIMARY_PACK      VARCHAR2(30 BYTE),
  USER_ID           NUMBER(10),
  ENTER_DT          DATE,
  PP_LN             NUMBER(8,2),
  PP_WD             NUMBER(8,2),
  PP_HT             NUMBER(8,2),
  MC_LN             NUMBER(8,2),
  MC_WD             NUMBER(8,2),
  MC_HT             NUMBER(8,2),
  PLACE_DISCH       VARCHAR2(100 BYTE),
  PBOM_CODE         VARCHAR2(5 BYTE)            NOT NULL,
  VP_UNIT_RATE      NUMBER(14,4),
  PROMO_MON         DATE,
  RM_COST           NUMBER,
  PM_COST           NUMBER,
  FOH_VC_COST       NUMBER,
  FOH_FC_COST       NUMBER,
  URM_COST          NUMBER,
  UPM_COST          NUMBER,
  UVC_COST          NUMBER,
  UFC_COST          NUMBER,
  MKT_TYPE          VARCHAR2(2 BYTE),
  PRICE_VALID_DATE  DATE,
  PAY_TERM_CONDI    VARCHAR2(100 BYTE),
  REMB_PRICE        NUMBER
)
TABLESPACE SMISEXP_DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


DROP TABLE SMISEXP.SYS_TEMP_FBT CASCADE CONSTRAINTS;

CREATE GLOBAL TEMPORARY TABLE SMISEXP.SYS_TEMP_FBT
(
  "SCHEMA"     VARCHAR2(32 BYTE),
  OBJECT_NAME  VARCHAR2(32 BYTE),
  OBJECT#      NUMBER,
  RID          UROWID(4000),
  ACTION       CHAR(1 BYTE)
)
ON COMMIT PRESERVE ROWS
NOCACHE;


DROP TABLE SMISEXP.G_ORDMAIN CASCADE CONSTRAINTS;

CREATE GLOBAL TEMPORARY TABLE SMISEXP.G_ORDMAIN
(
  ORD_NO        VARCHAR2(10 BYTE),
  CUST_CODE     VARCHAR2(7 BYTE),
  MPO_CODE      VARCHAR2(5 BYTE),
  MPO_ORDNO     VARCHAR2(10 BYTE),
  ORD_DATE      DATE,
  ACT_VALUE     NUMBER,
  DIS_VALUE     NUMBER,
  VAT_VALUE     NUMBER,
  NET_VALUE     NUMBER,
  INVOICED      VARCHAR2(1 BYTE),
  CUSTSIGN      VARCHAR2(1 BYTE),
  ORD_CDATE     DATE,
  TRNSTAT       VARCHAR2(1 BYTE),
  MKT_CODE      VARCHAR2(6 BYTE),
  DELI_DT       DATE,
  NO_ITEM       NUMBER(3),
  INVNO         VARCHAR2(10 BYTE),
  ORDNO_FLAG    VARCHAR2(1 BYTE),
  DELI_TIME     VARCHAR2(10 BYTE),
  ORD_REF       VARCHAR2(50 BYTE),
  TERI_CODE     VARCHAR2(5 BYTE),
  SR_CODE       VARCHAR2(5 BYTE),
  INVDATE       DATE,
  INV_TRNSTAT   VARCHAR2(1 BYTE),
  SALE_TYPE     VARCHAR2(1 BYTE),
  USER_ID       VARCHAR2(10 BYTE),
  ENTER_DT      DATE,
  IS_ADJUST     VARCHAR2(1 BYTE),
  PAYMENT_MODE  VARCHAR2(10 BYTE),
  CTYPE_PCT     NUMBER(8,2),
  MPO_CODE_OLD  VARCHAR2(5 BYTE),
  MKT_CODE_OLD  VARCHAR2(6 BYTE),
  IS_OFFER      VARCHAR2(1 BYTE),
  COMM_TP       NUMBER(12,2),
  MST_ORD_NO    VARCHAR2(10 BYTE)
)
ON COMMIT PRESERVE ROWS
NOCACHE;


DROP TABLE SMISEXP.G_ORDITEM CASCADE CONSTRAINTS;

CREATE GLOBAL TEMPORARY TABLE SMISEXP.G_ORDITEM
(
  ORD_NO         VARCHAR2(10 BYTE),
  P_CODE         VARCHAR2(5 BYTE),
  PROD_RATE      NUMBER(7,2),
  ORD_QNTY       NUMBER(6),
  INV_QNTY       NUMBER(6),
  ACT_VALUE      NUMBER(12,2),
  DIS_VALUE      NUMBER(8,2),
  VAT_VALUE      NUMBER(8,2),
  NET_VALUE      NUMBER(12,2),
  TRNSTAT        VARCHAR2(1 BYTE),
  PCAT_CODE      VARCHAR2(5 BYTE),
  PROD_VAT       NUMBER(7,2),
  INV_ACT_VALUE  NUMBER(12,2),
  USER_ID        VARCHAR2(10 BYTE),
  ENTER_DT       DATE,
  COMM_TP        NUMBER(12,2),
  MPO_CODE       VARCHAR2(5 BYTE),
  MST_ORD_NO     VARCHAR2(10 BYTE)
)
ON COMMIT PRESERVE ROWS
NOCACHE;


DROP TABLE SMISEXP.G_INVO_MAIN CASCADE CONSTRAINTS;

CREATE GLOBAL TEMPORARY TABLE SMISEXP.G_INVO_MAIN
(
  INVNO         VARCHAR2(10 BYTE),
  INVDATE       DATE,
  MPO_CODE      VARCHAR2(5 BYTE),
  MKT_CODE      VARCHAR2(6 BYTE),
  CUST_CODE     VARCHAR2(7 BYTE),
  EMPNO         VARCHAR2(6 BYTE),
  ACT_VALUE     NUMBER(12,2),
  DIS_VALUE     NUMBER(8,2),
  VAT_VALUE     NUMBER(8,2),
  NET_VALUE     NUMBER(12,2),
  TRNSTAT       VARCHAR2(1 BYTE),
  ORD_NO        VARCHAR2(10 BYTE),
  DELI_DATE     DATE,
  DELI_PER      VARCHAR2(6 BYTE),
  WHY_CANCEL    VARCHAR2(4 BYTE),
  CTYPE_PCT     NUMBER(6,2),
  ADJ_VALUE     NUMBER(15,2),
  SM_CHLNO      VARCHAR2(7 BYTE),
  SM_CHLDT      VARCHAR2(30 BYTE),
  PAID_STAT     VARCHAR2(1 BYTE),
  DELI_TIME     VARCHAR2(10 BYTE),
  VEHICLE_CODE  VARCHAR2(10 BYTE),
  DRV_EMP       VARCHAR2(6 BYTE),
  COIN_ADJ      NUMBER(10,2),
  TERI_CODE     VARCHAR2(5 BYTE),
  SALE_TYPE     VARCHAR2(1 BYTE),
  PAYMENT_MODE  VARCHAR2(10 BYTE),
  IS_ADJUST     VARCHAR2(1 BYTE),
  COMM_TP       NUMBER(12,2),
  MST_ORD_NO    VARCHAR2(10 BYTE),
  MST_INVNO     VARCHAR2(10 BYTE),
  USER_ID       VARCHAR2(10 BYTE),
  ENTER_DT      DATE
)
ON COMMIT PRESERVE ROWS
NOCACHE;


DROP TABLE SMISEXP.G_INVO_ITEM CASCADE CONSTRAINTS;

CREATE GLOBAL TEMPORARY TABLE SMISEXP.G_INVO_ITEM
(
  INVNO       VARCHAR2(10 BYTE),
  P_CODE      VARCHAR2(5 BYTE),
  PROD_BATCH  VARCHAR2(6 BYTE),
  INVO_QNTY   NUMBER(8),
  PROD_RATE   NUMBER(7,2),
  PROD_VAT    NUMBER(7,2),
  BONU_QNTY   NUMBER(4),
  ACT_VALUE   NUMBER(12,2),
  DIS_VALUE   NUMBER(8,2),
  VAT_VALUE   NUMBER(8,2),
  NET_VALUE   NUMBER(12,2),
  TRNSTAT     VARCHAR2(1 BYTE),
  STOK_QNTY   NUMBER(10),
  COMM_TP     NUMBER(12,2),
  MPO_CODE    VARCHAR2(5 BYTE),
  EMPNO       VARCHAR2(6 BYTE),
  ORD_NO      VARCHAR2(10 BYTE),
  MST_INVNO   VARCHAR2(10 BYTE),
  USER_ID     VARCHAR2(10 BYTE),
  ENTER_DT    DATE
)
ON COMMIT PRESERVE ROWS
NOCACHE;


CREATE UNIQUE INDEX SMISEXP.EXP_INVOMAIN_PK ON SMISEXP.EXP_INVOMAIN
(INVNO)
LOGGING
TABLESPACE SMISEXP_DATA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE UNIQUE INDEX SMISEXP.INVO_ITEM_PK ON SMISEXP.INVOITEM
(INVNO, P_CODE, PROD_BATCH)
LOGGING
TABLESPACE SMISEXP_DATA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE UNIQUE INDEX SMISEXP.INVO_MAIN_PK ON SMISEXP.INVOMAIN
(INVNO)
LOGGING
TABLESPACE SMISEXP_DATA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE UNIQUE INDEX SMISEXP.PK_CUSTOMER ON SMISEXP.CUSTOMER
(CUST_CODE)
LOGGING
TABLESPACE SMISEXP_DATA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE UNIQUE INDEX SMISEXP.PK_CUSTOMER1 ON SMISEXP.CUSTOMER_MV
(CUST_CODE)
LOGGING
TABLESPACE SMISEXP_DATA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE UNIQUE INDEX SMISEXP.PK_CUSTOMER_DTL ON SMISEXP.CUSTOMER_DTL
(CUST_CODE, CUST_ADDID)
LOGGING
TABLESPACE SMISEXP_DATA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE UNIQUE INDEX SMISEXP.PK_ORDMAIN ON SMISEXP.EXP_ORDMAIN
(ORD_NO)
LOGGING
TABLESPACE SMISEXP_DATA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE UNIQUE INDEX SMISEXP.PK_PRODUCT_EXP ON SMISEXP.PRODUCT_EXP
(PBOM_CODE)
LOGGING
TABLESPACE SMISEXP_DATA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE UNIQUE INDEX SMISEXP.PK_TENDER_MAIN ON SMISEXP.TENDER_MAIN
(TEND_CODE)
LOGGING
TABLESPACE SMISEXP_DATA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE UNIQUE INDEX SMISEXP.PRODUCT_EXP_PK ON SMISEXP.PRODUCT_EXP
(P_N_CODE)
LOGGING
TABLESPACE SMISEXP_DATA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE UNIQUE INDEX SMISEXP.PROD_GEN_PK ON SMISEXP.EXP_PROD_GEN
(GEN_MAIN_CODE, P_CODE)
LOGGING
TABLESPACE SMISEXP_DATA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE UNIQUE INDEX SMISEXP.SAM_PRODUCT_EXP_PK ON SMISEXP.SAM_PRODUCT_EXP
(SBOM_CODE)
LOGGING
TABLESPACE SMISEXP_DATA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


ALTER TABLE SMISEXP.EXP_ORDITEM
 DROP PRIMARY KEY CASCADE;

DROP TABLE SMISEXP.EXP_ORDITEM CASCADE CONSTRAINTS;

CREATE TABLE SMISEXP.EXP_ORDITEM
(
  ORD_NO         VARCHAR2(10 BYTE),
  P_CODE         VARCHAR2(4 BYTE),
  PBOM_CODE      VARCHAR2(5 BYTE),
  PTYPE_CODE     VARCHAR2(1 BYTE),
  GEN_MAIN_CODE  VARCHAR2(6 BYTE),
  ORD_QNTY       NUMBER,
  PRICE          NUMBER,
  PROD_VAT       NUMBER,
  ACT_VALUE      NUMBER,
  VAT_VALUE      NUMBER,
  DIS_VALUE      NUMBER,
  NET_VALUE      NUMBER,
  ENTRY_DT       DATE,
  USER_ID        VARCHAR2(10 BYTE),
  CNCL_FLAG      VARCHAR2(1 BYTE),
  CNCL_REASON    VARCHAR2(20 BYTE),
  CNCL_BY        VARCHAR2(10 BYTE),
  CNCL_DT        DATE,
  PRICE_VAL      VARCHAR2(20 BYTE),
  REG_VAL        VARCHAR2(20 BYTE)
)
TABLESPACE SMISEXP_DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          256K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


ALTER TABLE SMISEXP.EXP_QMAIN
 DROP PRIMARY KEY CASCADE;

DROP TABLE SMISEXP.EXP_QMAIN CASCADE CONSTRAINTS;

CREATE TABLE SMISEXP.EXP_QMAIN
(
  QUOTE_CODE        VARCHAR2(10 BYTE),
  QUOTE_DATE        DATE,
  TEND_NO           VARCHAR2(20 BYTE),
  TEND_CODE         VARCHAR2(10 BYTE),
  CUST_CODE         VARCHAR2(10 BYTE),
  ISSUE_DT          DATE,
  SUBM_DT           DATE,
  FC_COST           NUMBER,
  NOF_CONT          NUMBER,
  SIZE_OF_CONT      NUMBER,
  GOV_LAB_COST      NUMBER,
  GOV_RPT_NOF_DAYS  NUMBER,
  COP_PCT           NUMBER,
  LOCAL_AGENT       VARCHAR2(20 BYTE),
  COM_PCT           NUMBER,
  PER_BOND_COST     NUMBER,
  BANK_CHARGE       NUMBER,
  EXC_RATE          NUMBER,
  TOT_UNIT          NUMBER,
  USER_ID           VARCHAR2(5 BYTE),
  ENTER_DT          DATE,
  BID_FEE           NUMBER,
  L_AWARD_PRICE     NUMBER
)
TABLESPACE SMISEXP_DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


ALTER TABLE SMISEXP.EXP_INVOITEM
 DROP PRIMARY KEY CASCADE;

DROP TABLE SMISEXP.EXP_INVOITEM CASCADE CONSTRAINTS;

CREATE TABLE SMISEXP.EXP_INVOITEM
(
  INVNO        VARCHAR2(10 BYTE),
  P_CODE       VARCHAR2(4 BYTE),
  PBOM_CODE    VARCHAR2(5 BYTE),
  INVO_QNTY    NUMBER,
  PRICE        NUMBER,
  PROD_VAT     NUMBER,
  ACT_VALUE    NUMBER,
  VAT_VALUE    NUMBER,
  DIS_VALUE    NUMBER,
  NET_VALUE    NUMBER,
  ENTRY_DT     DATE,
  USER_ID      VARCHAR2(10 BYTE),
  TRNSTAT      VARCHAR2(1 BYTE),
  CNCL_FLAG    VARCHAR2(1 BYTE),
  CNCL_REASON  VARCHAR2(100 BYTE),
  CNCL_BY      VARCHAR2(10 BYTE),
  CNCL_DATE    DATE
)
TABLESPACE SMISEXP_DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX SMISEXP.EXP_INVOITEM_PK ON SMISEXP.EXP_INVOITEM
(INVNO, P_CODE, PBOM_CODE)
LOGGING
TABLESPACE SMISEXP_DATA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE UNIQUE INDEX SMISEXP.PK_EXP_QMAIN ON SMISEXP.EXP_QMAIN
(QUOTE_CODE)
LOGGING
TABLESPACE SMISEXP_DATA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE UNIQUE INDEX SMISEXP.PK_ORDITEM ON SMISEXP.EXP_ORDITEM
(ORD_NO, P_CODE, PBOM_CODE)
LOGGING
TABLESPACE SMISEXP_DATA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          128K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


ALTER TABLE SMISEXP.EXP_QITEM
 DROP PRIMARY KEY CASCADE;

DROP TABLE SMISEXP.EXP_QITEM CASCADE CONSTRAINTS;

CREATE TABLE SMISEXP.EXP_QITEM
(
  QUOTE_CODE    VARCHAR2(10 BYTE),
  P_CODE        VARCHAR2(5 BYTE),
  P_N_CODE      VARCHAR2(5 BYTE),
  UNIT_CODE     VARCHAR2(2 BYTE),
  OFFERED_RATE  NUMBER,
  QNTY_BOX      NUMBER,
  UTP           NUMBER,
  UVP           NUMBER,
  COMM_TP       NUMBER,
  COMM_VP       NUMBER,
  RM_COST       NUMBER,
  PM_COST       NUMBER,
  FOH_VC_COST   NUMBER,
  FOH_FC_COST   NUMBER,
  FC_COST_PCT   NUMBER,
  USER_ID       VARCHAR2(5 BYTE),
  ENTER_DT      DATE
)
TABLESPACE SMISEXP_DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX SMISEXP.PK_EXP_QITEM ON SMISEXP.EXP_QITEM
(QUOTE_CODE, P_N_CODE)
LOGGING
TABLESPACE SMISEXP_DATA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


ALTER TABLE SMISEXP.CUSTOMER ADD (
  CONSTRAINT PK_CUSTOMER
 PRIMARY KEY
 (CUST_CODE)
    USING INDEX 
    TABLESPACE SMISEXP_DATA
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                NEXT             1M
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                PCTINCREASE      0
               ));

ALTER TABLE SMISEXP.CUSTOMER_DTL ADD (
  CONSTRAINT PK_CUSTOMER_DTL
 PRIMARY KEY
 (CUST_CODE, CUST_ADDID)
    USING INDEX 
    TABLESPACE SMISEXP_DATA
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                NEXT             1M
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                PCTINCREASE      0
               ));

ALTER TABLE SMISEXP.CUSTOMER_MV ADD (
  CONSTRAINT PK_CUSTOMER1
 PRIMARY KEY
 (CUST_CODE)
    USING INDEX 
    TABLESPACE SMISEXP_DATA
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                NEXT             1M
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                PCTINCREASE      0
               ));

ALTER TABLE SMISEXP.EXP_ORDMAIN ADD (
  CONSTRAINT PK_ORDMAIN
 PRIMARY KEY
 (ORD_NO)
    USING INDEX 
    TABLESPACE SMISEXP_DATA
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                NEXT             1M
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                PCTINCREASE      0
               ));

ALTER TABLE SMISEXP.INVOITEM ADD (
  CONSTRAINT INVO_ITEM_PK
 PRIMARY KEY
 (INVNO, P_CODE, PROD_BATCH)
    USING INDEX 
    TABLESPACE SMISEXP_DATA
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                NEXT             1M
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                PCTINCREASE      0
               ));

ALTER TABLE SMISEXP.INVOMAIN ADD (
  CONSTRAINT INVO_MAIN_PK
 PRIMARY KEY
 (INVNO)
    USING INDEX 
    TABLESPACE SMISEXP_DATA
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                NEXT             1M
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                PCTINCREASE      0
               ));

ALTER TABLE SMISEXP.PRODUCT_EXP ADD (
  CONSTRAINT PRODUCT_EXP_PK
 PRIMARY KEY
 (P_N_CODE)
    USING INDEX 
    TABLESPACE SMISEXP_DATA
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                NEXT             1M
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                PCTINCREASE      0
               ),
  CONSTRAINT PRODUCT_EXP_UNQ
 UNIQUE (PBOM_CODE) DISABLE);

ALTER TABLE SMISEXP.SAM_PRODUCT_EXP ADD (
  CONSTRAINT SAM_PRODUCT_EXP_PK
 PRIMARY KEY
 (SBOM_CODE)
    USING INDEX 
    TABLESPACE SMISEXP_DATA
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                NEXT             1M
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                PCTINCREASE      0
               ));

ALTER TABLE SMISEXP.TENDER_MAIN ADD (
  CONSTRAINT PK_TENDER_MAIN
 PRIMARY KEY
 (TEND_CODE)
    USING INDEX 
    TABLESPACE SMISEXP_DATA
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                NEXT             1M
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                PCTINCREASE      0
               ));

ALTER TABLE SMISEXP.EXP_INVOMAIN ADD (
  CONSTRAINT EXP_INVOMAIN_PK
 PRIMARY KEY
 (INVNO)
    USING INDEX 
    TABLESPACE SMISEXP_DATA
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                NEXT             1M
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                PCTINCREASE      0
               ));

ALTER TABLE SMISEXP.EXP_PROD_GEN ADD (
  CONSTRAINT PROD_GEN_PK
 PRIMARY KEY
 (GEN_MAIN_CODE, P_CODE)
    USING INDEX 
    TABLESPACE SMISEXP_DATA
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                NEXT             1M
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                PCTINCREASE      0
               ));

ALTER TABLE SMISEXP.EXP_ORDITEM ADD (
  CONSTRAINT PK_ORDITEM
 PRIMARY KEY
 (ORD_NO, P_CODE, PBOM_CODE)
    USING INDEX 
    TABLESPACE SMISEXP_DATA
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          128K
                NEXT             1M
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                PCTINCREASE      0
               ));

ALTER TABLE SMISEXP.EXP_QMAIN ADD (
  CONSTRAINT PK_EXP_QMAIN
 PRIMARY KEY
 (QUOTE_CODE)
    USING INDEX 
    TABLESPACE SMISEXP_DATA
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                NEXT             1M
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                PCTINCREASE      0
               ));

ALTER TABLE SMISEXP.EXP_INVOITEM ADD (
  CONSTRAINT EXP_INVOITEM_PK
 PRIMARY KEY
 (INVNO, P_CODE, PBOM_CODE)
    USING INDEX 
    TABLESPACE SMISEXP_DATA
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                NEXT             1M
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                PCTINCREASE      0
               ));

ALTER TABLE SMISEXP.EXP_QITEM ADD (
  CONSTRAINT PK_EXP_QITEM
 PRIMARY KEY
 (QUOTE_CODE, P_N_CODE)
    USING INDEX 
    TABLESPACE SMISEXP_DATA
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                NEXT             1M
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                PCTINCREASE      0
               ));

ALTER TABLE SMISEXP.EXP_ORDITEM ADD (
  CONSTRAINT FK_ORDITEM 
 FOREIGN KEY (ORD_NO) 
 REFERENCES SMISEXP.EXP_ORDMAIN (ORD_NO));

ALTER TABLE SMISEXP.EXP_QMAIN ADD (
  CONSTRAINT FK_EXP_QMAIN 
 FOREIGN KEY (TEND_CODE) 
 REFERENCES SMISEXP.TENDER_MAIN (TEND_CODE));

ALTER TABLE SMISEXP.EXP_INVOITEM ADD (
  CONSTRAINT FK_EXP_INVOITEM 
 FOREIGN KEY (INVNO) 
 REFERENCES SMISEXP.EXP_INVOMAIN (INVNO));

ALTER TABLE SMISEXP.EXP_QITEM ADD (
  CONSTRAINT FK_EXP_QITEM 
 FOREIGN KEY (QUOTE_CODE) 
 REFERENCES SMISEXP.EXP_QMAIN (QUOTE_CODE));

GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON SMISEXP.PRODUCT_EXP TO ACSMS;

GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON SMISEXP.SAM_PRODUCT_EXP TO ACSMS;

GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON SMISEXP.PRODUCT_EXP TO APBMS;

GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON SMISEXP.SAM_PRODUCT_EXP TO APBMS;

GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON SMISEXP.PRODUCT_EXP TO ASCSMS;

GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON SMISEXP.SAM_PRODUCT_EXP TO ASCSMS;

GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON SMISEXP.PRODUCT_EXP TO ASMIS;

GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON SMISEXP.SAM_PRODUCT_EXP TO ASMIS;

GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON SMISEXP.PRODUCT_EXP TO ASMIS_NPL;

GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON SMISEXP.SAM_PRODUCT_EXP TO ASMIS_NPL;

GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON SMISEXP.PRODUCT_EXP TO ATDMS;

GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON SMISEXP.SAM_PRODUCT_EXP TO ATDMS;

GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON SMISEXP.PRODUCT_EXP TO CMRC;

GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON SMISEXP.SAM_PRODUCT_EXP TO CMRC;

GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON SMISEXP.PRODUCT_EXP TO CMRCBOM;

GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON SMISEXP.SAM_PRODUCT_EXP TO CMRCBOM;

GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON SMISEXP.PRODUCT_EXP TO CSMS;

GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON SMISEXP.SAM_PRODUCT_EXP TO CSMS;

GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON SMISEXP.PRODUCT_EXP TO DRUG;

GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON SMISEXP.SAM_PRODUCT_EXP TO DRUG;

GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON SMISEXP.PRODUCT_EXP TO ERP;

GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON SMISEXP.SAM_PRODUCT_EXP TO ERP;

GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON SMISEXP.PRODUCT_EXP TO FGS;

GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON SMISEXP.SAM_PRODUCT_EXP TO FGS;

GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON SMISEXP.PRODUCT_EXP TO GL;

GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON SMISEXP.SAM_PRODUCT_EXP TO GL;

GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON SMISEXP.PRODUCT_EXP TO GLHCL;

GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON SMISEXP.SAM_PRODUCT_EXP TO GLHCL;

GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON SMISEXP.PRODUCT_EXP TO INST;

GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON SMISEXP.SAM_PRODUCT_EXP TO INST;

GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON SMISEXP.CUSTOMER TO MIS;

GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON SMISEXP.EXP_CASH TO MIS;

GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON SMISEXP.EXP_ORDMAIN TO MIS;

GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON SMISEXP.INVOITEM TO MIS;

GRANT SELECT ON SMISEXP.PRODUCT_EXP TO MIS WITH GRANT OPTION;
GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON SMISEXP.PRODUCT_EXP TO MIS;

GRANT SELECT ON SMISEXP.SAM_PRODUCT_EXP TO MIS WITH GRANT OPTION;
GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON SMISEXP.SAM_PRODUCT_EXP TO MIS;

GRANT SELECT ON SMISEXP.PRODUCT_EXP TO NPL WITH GRANT OPTION;
GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON SMISEXP.PRODUCT_EXP TO NPL;

GRANT SELECT ON SMISEXP.SAM_PRODUCT_EXP TO NPL WITH GRANT OPTION;
GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON SMISEXP.SAM_PRODUCT_EXP TO NPL;

GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON SMISEXP.PRODUCT_EXP TO NPLA;

GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON SMISEXP.SAM_PRODUCT_EXP TO NPLA;

GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON SMISEXP.PRODUCT_EXP TO NPLEPF;

GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON SMISEXP.SAM_PRODUCT_EXP TO NPLEPF;

GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON SMISEXP.PRODUCT_EXP TO PMIS;

GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON SMISEXP.SAM_PRODUCT_EXP TO PMIS;

GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON SMISEXP.PRODUCT_EXP TO QCMS;

GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON SMISEXP.SAM_PRODUCT_EXP TO QCMS;

GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON SMISEXP.PRODUCT_EXP TO QCMSAHD;

GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON SMISEXP.SAM_PRODUCT_EXP TO QCMSAHD;

GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON SMISEXP.PRODUCT_EXP TO QCMSHCL;

GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON SMISEXP.SAM_PRODUCT_EXP TO QCMSHCL;

GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON SMISEXP.PRODUCT_EXP TO SCSMS;

GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON SMISEXP.SAM_PRODUCT_EXP TO SCSMS;

GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON SMISEXP.PRODUCT_EXP TO SMIS;

GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON SMISEXP.SAM_PRODUCT_EXP TO SMIS;

GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON SMISEXP.PRODUCT_EXP TO SMIS_NPL;

GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON SMISEXP.SAM_PRODUCT_EXP TO SMIS_NPL;

GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON SMISEXP.PRODUCT_EXP TO WHRP;

GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON SMISEXP.SAM_PRODUCT_EXP TO WHRP;

GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON SMISEXP.PRODUCT_EXP TO WHRPAHD;

GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON SMISEXP.SAM_PRODUCT_EXP TO WHRPAHD;

GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON SMISEXP.PRODUCT_EXP TO WHRPHCL;

GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON SMISEXP.SAM_PRODUCT_EXP TO WHRPHCL;

